### ISSUE TITLE
libnotify support for *optional* update notifications

### ISSUE THREAD

**Issue by Trucido** [linuxmint/mintupdate#103]
Sorry again if this is the wrong place to post feature requests, but it'd be kinda nice to have notify support when updates are available, perhaps configurable to only notify on certain levels - i.e. important security, or none at all if the user doesn't wish to be disturbed. I understand mintUpdate is designed to be as unobtrusive as possible, unlike Ubuntu's update-notifier - which is why this should be optional or limited to only important updates.

my python skills are not all that great, though using gentoo for years you pick up a lot, i'd be happy to help submit patches if someone could point me in the right direction (if this is a worthwhile feature people would want).

**Comment by JosephMcc** [comment]
I kind of like this idea. It would allow me to just remove it from my system tray.

**Comment by xenopeek** [comment]
Does this go with #101?

**Comment by JosephMcc** [comment]
Sort of. I think the idea here though it send notifications instead of relying on systray or indicators to show you when an update is available.

My thought would be to have some tool run every "x" amount of time to check for updates. If there are some, pop up a notification saying so that allows me to run mintupdate. This would also keep me from having to have mint update running at all times. No idea if there is any desire to even implement this sort of thing though.

**Comment by xenopeek** [comment]
Thanks for contributing to mintupdate. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by xenopeek** [comment]
Thanks for contributing to mintupdate. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
