### ISSUE TITLE
Use ngettext for plurals

### ISSUE THREAD

**Issue by gunchleoc** [linuxmint/mintupdate#110]
Could you please merge the following 2 strings into 1 string and fetch the translation with ngettext for proper plural forms?

```
This update contains %d packages: 
```

Located in usr/lib/linuxmint/mintUpdate/mintUpdate.py:1880 usr/lib/linuxmint/mintUpdate/mintUpdate.py:1910 

```
This update contains 1 package: 
```

Located in usr/lib/linuxmint/mintUpdate/mintUpdate.py:1883 usr/lib/linuxmint/mintUpdate/mintUpdate.py:1913 

Related Launchpad bug: https://bugs.launchpad.net/linuxmint/+bug/1390481

ETA: I found another 2 strings that need to be combined with ngettext in the same way:

```
%(selected)d update selected (%(size)s)
```

Located in usr/lib/linuxmint/mintUpdate/mintUpdate.py:966 usr/lib/linuxmint/mintUpdate/mintUpdate.py:1951

```
%(selected)d updates selected (%(size)s)
```

Located in usr/lib/linuxmint/mintUpdate/mintUpdate.py:968 usr/lib/linuxmint/mintUpdate/mintUpdate.py:1953

And the following strings also need to be fetched with ngettext:

```
The following %d packages will be removed:
```

Located in usr/lib/linuxmint/mintUpdate/mintUpdate.py:345

```
The following %d packages will be installed:
```

Located in usr/lib/linuxmint/mintUpdate/mintUpdate.py:375

```
%(recommended)d recommended updates available (%(size)s)
```

Located in usr/lib/linuxmint/mintUpdate/mintUpdate.py:864

```
%(recommended)d recommended updates available (%(size)s), 1 ignored
```

Located in usr/lib/linuxmint/mintUpdate/mintUpdate.py:866

```
%(recommended)d recommended updates available (%(size)s), %(ignored)d ignored
```

Located in usr/lib/linuxmint/mintUpdate/mintUpdate.py:868

**Comment by clefebvre** [comment]
Thanks.. just one thing I'm a bit worried about.

I've seen many translaters drop the argument in ngettext msgstrs for cardinality 1 (or even 2 and 3 in Arabic). Although that's ok in C (where printf basically dismisses the excess of unmatched arguments), it's not OK at all in Python.

So we probably need to interface the call to ngettext here with a wrapper which takes care of that.

i.e. if we call ngettext("%d update" % num, "%d updates", num) and the msgstr for this when num is 1, is:

"1 update", instead of "%d update".. we've a problem and we don't want to end up with an exception.
