### ISSUE TITLE
Inappropriate column label "Level"

### ISSUE THREAD

**Issue by martinszy** [linuxmint/mintupdate#136]
Hello, every time I look at the updates screen and see the numbers on the level column I'm never sure what they mean. The column label doesn't help... Level of what? When I read the help and understood it's about risky updates, then I started to find the label of the column inappropriate.
If you agree, please fix it.
I suggest "Risk" as the most.

BTW: I use it in spanish, so my actual column name is "Nivel" and I suggest to change it to "Riesgo".

**Comment by EduardDopler** [comment]
I had the same discussion with a German translator. In German, that first translator used *"Ebene"* which most Germans associate with either *floor*/*platform*, *plane* or *layer*.
I agree that many non-geek users are unfamiliar with the term Level in that use case. All the level is about is the probability of damaging my system, so why not renaming it to *safety level* or *risk level*? In German this would correspond to *"Risikostufe"*. Together with the icons' colors a novice would intuitively know what it means.
But renaming such a major term in Mint... I doubt your suggestion will make it to the dozens of translations which would need adaption then. Good luck though!

**Comment by kneekoo** [comment]
The problem is that the way we perceive "Level" and "Risk" are opposites, so it would become really confusing with the current ratings of 1-5. When you think about a level, the lower it is, the less the effect/impact. And when you consider risks, a risk level 1 would be the top level risk. So this one is tricky to play with.

I agree, "Level" doesn't say anything to the uninformed user. But after you know what it is, you will simply ignore it and only take it as a text label, because you know what level numbers you should avoid.

**Comment by EduardDopler** [comment]
Risk Score?

**Comment by kneekoo** [comment]
Ideally it should be one word. Labels that make columns wider than the actual content should be avoided whenever possible. To be honest, for me it would make much more sense to have an extra button on the toolbar - "Explain" or whatever - that would explain in just a few words what everything means. Because once the users know, this becomes a non-issue.

The actual issue is that it's not intuitive enough but not everything can be intuitive in 1-2 short words. We have to keep in mind that the concept of risk levels is not something used everywhere. That's why it's difficult to make it clear in 1-2 words, even if we name it "Risk Level" or "Risk Score".

To be realistic, in an update software I would avoid using words with powerful negative connotation because most people don't get into details and if they develop some kind of fear of updating just because they are afraid of some risks, then we are doing more harm than good by changing a simple name of a label.

**Comment by EduardDopler** [comment]
@kneekoo You're right. I'd favor a clickable icon (with a cursor indicating that it is clickable) together with a tooltip.

**Comment by martinszy** [comment]
I like the suggestion of having help, but a toolbar button is far too
removed from the information, so here's another idea: Make use of the
tooltop. Right now the risk level number has the same tooltip as the first
column "software update" or "security update". What if we make this icon
have to tooltip that says something along the lines of: "Risk level 5: It
may cause problems, handle with care".
I would still argue that column name is confusing.
And this argument " avoid using words with powerful negative connotation
because most people don't get into details and if they develop some kind of
fear of updating just because they are afraid of some risks, then we are
doing more harm than good by changing a simple name of a label."
I agree that we should not create fear, but causing confusion is not the
best way to avoid fear. The best way is to be clear.
We still have a red icon with a 5 in it ... isn't that specifically
designed to raise an alarm? So we are trying to alert the user at least in
this way.
So maybe change the icons to words? Like "Safe" "Risky" "Apply manually". I
know this is a bit out of scope for the original issue, but there doesn't
seem to be a solid reason for the way it's presented now.

Martín.

**Comment by kneekoo** [comment]
In my opinion, there is no simple way to make everything clear without bloating the Update Manager. Once you know what those levels mean, having numbers and color codes are enough and very efficient. So why not educate the users instead of bloating the software?

On the first start (ever, not after boot), the Update Manager could ask the user if they need information about the interface and tell them the information will always be available by clicking the "Explain" button from the toolbar. The help tells you everything about risk levels anyway, so the extra button would be redundant anyway, but even that is better than anything else.

**Comment by JosephMcc** [comment]
This has changed some. On first run you are presented with some preset options for how you want updates handled. I don't really see an issue with calling the column "Level" and not sure I see a better solution here.

I'm all for things being intuitive but at some point users need to learn how to use a piece of software. We don't need "Explain" buttons in the toolbar. There is a menu item called "Help" that can be used and is fairly universal in applications.
