### ISSUE TITLE
Insecure permissions in /tmp/mintUpdate/

### ISSUE THREAD

**Issue by ricardobranco777** [linuxmint/mintupdate#155]
The directory and its contents are world writable. 

The offending code can be found with:

grep chmod /usr/lib/linuxmint/mintUpdate/mintUpdate.py

**Comment by xenopeek** [comment]
mintupdate writes its logging to that directory. Nothing is read from it. Multiple users on the same computer can use mintupdate and so that directory needs to be writable for all users. As the user is in fact the owner of that log file, it doesn't really matter whether it is world writable or not I think. If there were some malicious program running in the user's session it could modify that log file as the user themselves can.

I think this issue can be closed.

**Comment by ricardobranco777** [comment]
The 1777 permissions, as used in /tmp, would be a better choice for the directory and 644 for the files created by MintUpdate.

**Comment by xenopeek** [comment]
Editing that file as follows would achieve that:
```
    def __init__(self):
        logdir = "/tmp/mintUpdate/"
        if not os.path.exists(logdir):
            os.system("mkdir -p " + logdir)
#           os.system("chmod a+rwx " + logdir)
            os.system("chmod a+rwt " + logdir)
        self.log = tempfile.NamedTemporaryFile(mode = 'w', prefix = logdir, delete=False)
        try:
#           os.system("chmod a+rw %s" % self.log.name)
            os.system("chmod a+r,u+w %s" % self.log.name)
        except Exception as e:
            print (e)
            print(sys.exc_info()[0])
```
