### ISSUE TITLE
APT cache is broken due to "weak digest algorithm" on Ubuntu 16.04.

### ISSUE THREAD

**Issue by KoczurekK** [linuxmint/mintupdate#161]
I added Linux Mint 18 Sarah repo to my system, here's /etc/apt/sources.list.d/mint.list:
deb http://packages.linuxmint.com/ sarah main import backport

When i try to update packages lists using mintupdate i get those errors:
W: http://dl.google.com/linux/chrome/deb/dists/stable/Release.gpg: Signature by key 4CCA1EAF950CEE4AB83976DCA040830F7FAC5991 uses weak digest algorithm (SHA1)
W: http://dl.google.com/linux/chrome/deb/dists/stable/Release.gpg: Signature by key 3B068FB4789ABE4AEFA3BB491397BC53640DB551 uses weak digest algorithm (SHA1)
W: http://packages.linuxmint.com/dists/sarah/Release.gpg: Signature by key E1A38B8F144675D060EA666F3EE67F3D0FF405B2 uses weak digest algorithm (SHA1)

**Comment by rugbybrat04** [comment]
I'm having a similar issue, ever since i updated to Sarah about two weeks ago (for some reason It keeps saying rosa for all of my info even though when i boot it comes up as sarah).

W: http://extra.linuxmint.com/dists/rosa/Release.gpg: Signature by key E1A38B8F144675D060EA666F3EE67F3D0FF405B2 uses weak digest algorithm (SHA1)
W: http://packages.linuxmint.com/dists/rosa/Release.gpg: Signature by key E1A38B8F144675D060EA666F3EE67F3D0FF405B2 uses weak digest algorithm (SHA1)

**Comment by brennanhm** [comment]
[Debian dropped support for SHA1 signed repositories back in March](https://juliank.wordpress.com/2016/03/14/dropping-sha-1-support-in-apt/). Ubuntu 16.04, which Linux Mint 18 Sarah is based on, included this update.

I added the Sarah repo to a fresh install of Ubuntu 16.04 as described by the OP. I then [installed the latest Mint respository signing key](http://askubuntu.com/questions/507707/how-to-add-linuxmint-repositories-to-ubuntu) (released May 24th) and see no warning messages when updating the APT cache. My guess is that the repo signature for Sarah has been strengthened since this issue was originally reported.

The warnings do show up if I use the previous repo, Rosa.
