### ISSUE TITLE
background of mintUpdate-panel-icon not green if hovered

### ISSUE THREAD

**Issue by NikoKrause** [linuxmint/mintupdate#164]
In Linux Mint 18 Cinnamon Beta the background of icons in the panel gets green if hovered with mouse:
![bildschirmfoto vom 2016-06-15 13-25-23](https://cloud.githubusercontent.com/assets/8415124/16078114/1e045958-32fd-11e6-81ad-37fa997f2b05.png)

But mintUpdate is the only icon, which behaves not that way:
![bildschirmfoto vom 2016-06-15 13-25-12](https://cloud.githubusercontent.com/assets/8415124/16078126/3eed6c04-32fd-11e6-88cc-29c6a20cdf78.png)

**Comment by JosephMcc** [comment]
This isn't really a bug in mintupdate. The icon sits in the Cinnamon system tray and the items there are not the same as a normal Cinnamon applet. That's why you don't get the hover effect. If anything this would be a bug in Cinnamon but I'm not sure how much can be done. If you search the Cinnamon issues for "systray" you will find that it's a bit delicate and a challenge just to have working correctly.
