### ISSUE TITLE
Mint 18: Update Manager creates objects with wrong ownership

### ISSUE THREAD

**Issue by Cos-mo** [linuxmint/mintupdate#169]
Test system: LM 18 Cinnamon 64 bit. Fresh installation, no previous home content used.

Doing a refresh of the update manager creates in ~/.cache the folder dconf with the file user, both with wrong ownership by root.

Steps to reproduce:
Install the system and boot into.
~.cache does exist with the sub-folders fontconfig and wallpaper othe with correct ownership.
Open the update manager and select the policy: Still the same content for .cache.
Do a refresh in the update manager: the folder dconf with root ownership gets created. No other action has been taken, no switch of mirrors or anything else.

Conclusion: the bug is caused by the update manager.

**Comment by DaveLessnau** [comment]
Just installed LM 18 Cinnamon x32 on a laptop and saw the same thing.  In my case, I didn't find it until after I'd done a few things in the Terminal.  But, after reviewing the Terminal history, there's nothing in there (sudo vs gksudo, for instance) that would have caused this.  I did do a Refresh in the Update Manager, so I'll agree with Cos-mo.

**Comment by xenopeek** [comment]
I believe this is caused by mintUpdate.py running checkAPT.py with `sudo` here: https://github.com/linuxmint/mintupdate/blob/master/usr/lib/linuxmint/mintUpdate/mintUpdate.py#L767. checkAPT.py is called when you click the Refresh button in mintupdate. Testing with mintupdate 5.1.0.

If the directory ~/.cache/dconf/ doesn't exist:
- Start mintupdate and click the Refresh button
- After Refresh completes the directory ~/.cache/dconf/ will have been created and is owned by root

If the directory ~/.cache/dconf/ does exist and is owned by the user themselves:
- Start mintupdate and click the Refresh button
- After Refresh completes the directory ~/.cache/dconf/ will still be owned by the user themselves but the file ~/.cache/dconf/user will have been created and is owned by root

If the directory ~/.cache/dconf/ does exist as does the file ~/.cache/config/user and both are owned by the user themselves, then running mintupdate Refresh won't change any ownership.

As such a possible solution would be to just before where mintUpdate.py uses sudo to call checkAPT.py, to create that directory and file:

```
            if not os.path.isdir(os.path.expanduser("~/.cache/dconf")):
                os.makedirs(os.path.expanduser("~/.cache/dconf"))
            if not os.path.exists(os.path.expanduser("~/.cache/dconf/user")):
                open(os.path.expanduser("~/.cache/dconf/user"), "w").close()
```

In my testing that appears to work. However if you Google on this issue, of graphical programs being run as root changing ownership of gsettings files ~/.cache/dconf/user or ~/.config/dconf/user in the user's own directory to root, you'll find this is an issue that affects other programs. E.g., if you run `gksudo gedit` your ~/.config/dconf/user file now belongs to root. So is this an issue in mintupdate or in gsettings?

**Comment by Cos-mo** [comment]
@xenopeek Your detailed description matches with my observation.

Additional question: Why does the problem happen only in UM 5.x, not until 4.9.9.1?

**Comment by xenopeek** [comment]
Good addition. I downgraded to mintupdate 4.9.9.1 on Linux Mint 18 (also needed to install mint-kernel-info from Linux Mint 17.3) and doing a Refresh on that doesn't create a ~/.cache/dconf/ directory. (The ~/.config/dconf directory and ~/.config/dconf/user file aren't created if they don't exist nor do they change ownership if they do.)

So I think we can rule out other changes in the operating system.

**Comment by Cos-mo** [comment]
New finding in this context:

If I do a refresh of UM and open the folder ~/.cache/dconf in nemo with elevated rights (right click in nemo -> open as administrator), the file user vanishes. If I leave this elevated nemo window open and do a refresh of UM the file gets back; if I now close the elevated nemo window, the file nemo vanishes also. In every case the folder dconf remains as empty folder.

Checks about the content of dconf done with ls in the terminal.

If I repeat the described actions, the results can be reproduced at 100 %.

I also tested, if the problem of the vanishing file differs, if I leave the wrong ownership of dcnf and user or if I correct them; result: it does not matter.

BTW: the size of user is only 2 byte, so nothing really useful seems to get stored there.

This new finding - originated by the report of a user in https://forums.linuxmint.com/viewtopic.php?p=1213359#p1213359 - merely looks like a nemo bug. I did report it here, as there might be a relationship between the original issue and the new finding. Also I do not see this problem of vanishing files in other folders in user's home.

**Comment by KirkM** [comment]
I'm the original user that first reported the problem Cos-mo references in the above comment and that has helped troubleshoot this problem throughout the referenced thread. I just wanted to add that this "user" file that's created, when opened in Libreoffice (the text editor, xed, cannot recognize the format), the only thing "user" contains is the following:

> ##

I realize this does not help in further troubleshooting the problem but perhaps it's relevant knowing what the file contains anyway.

**Comment by Cos-mo** [comment]
Today I came across a new observation. It may be related to the bug described here or not - I cannot judge. At least it looks really strange.

The observation is the file with the (strange) name: sudo_as_admin_successful in the user's home, which I happened to see today. It is a text file with 0 byte size. Ownership and permissions are as expected, that means owned by the user, user has read/write access, all others have read access. No execute permission for anybody.

Investigating deeper I found, that this file gets created, as soon as the update manager does a refresh. If I delete it and do a refresh from the context menu of the tray icon of UM with Nemo open I see this file appearing in the same second, when I start the refresh.

The common thing with the user file (s described above) is, that creation gets triggered by the UM refresh.
The strange file name sounds suspicious. I may be wrong, but it sounds, as if UM does check during refresh, if the user is in the sudo group (why does UM check this at this point at all?). My suspicion is, that the user file with wrong ownership does also get created for this check.
My assumptions get hardened by the finding, that if I do a refresh in a second account **without** sudo membership both files (sudo_as_admin_successull and .cache/dconf/user do **not** get created.

**Comment by Cos-mo** [comment]
Tested again with Mint 18.2 beta Cinnamon 64 bit:

No change The bug still persists.

**Comment by Cos-mo** [comment]
Mint 18.2 beta Cinnamon 64 bit.

I found, that in the guest account neither the dconf folder (in ~/.cache) nor the file .sudo_as_admin_succesful (in ~/) get created. Perhaps somebody can draw a conclusion out of it.

**Comment by Cos-mo** [comment]
I investigated a little bit deeper and found this solution, which seems to work following my tests:

I added in line 605 of the file mintUpdate.py (as given by xenopeek above) the sudo parameter -H. Resulting in
`refresh_command = "sudo -H %s" % refresh_command`
Doing a test with update manager 5.2.9 demonstrates, that the folder dconf in user's .cache does not more get created. Also I did not find any negative side effect. Only this strange file sudo_as_admin_successful still gets created, when I refresh the update manager.

In the hope, that this finding finally leads to the result, that the bug gets fixed.

**Comment by Cos-mo** [comment]
I found, that the small code change I suggested above, leads to a new problem, which I reported [here](url) (in error).

But this leads to the question, why are the settings for UM stored in user context at all? IMHO this makes no sense (perhaps with the exception to show the tray icon only in case of available updates). If the settings would get stored centrally, the problem of seemingly ignored ignore list would probably not happen.

**Comment by Cos-mo** [comment]
With Mint 19 C 64 beta the bug got far more serious, affecting now also DBus and potentially also GVFS.

1. Additionally to the objects given above with a refresh of the update manager also ~/.dbus gets created with root ownership. This happens only with the automatic refresh (by default 10 minutes after launch), not with manual refreshing.

2. In case, that ~/.dbus with root ownership does exist, the attempt to open in Nemo a folder pane as root via right click menu in the folder pane, creates 2 more objects: ~/.gvfs and ~/.cache/doc with root ownership; sometimes this happens only after the 2nd or 3rd try after login out and back into the account. If those 2 objects have been created, the system is totally confused about them: the command ls -la cannot display the owners and not the permissions or any other property except, that they are folders. But Nemo disagrees and says, that they are binary objects. Consequently (without knowing owner and permission) it is not possible to delete those objects, not even with root permission. Only after logging out and back into the account the properties get displayed.

If ~/.gvfs does exist with root ownership, the attempt to open a Nemo window as root leads to the result, that the elevated window displays the content of /root instead of the marked folder. This does not happen always, but e. g. in ~/.cache.

I did a counter-check with a second account on that system, where I disabled update manager in the autostart list. None of the above given problems occur there, also opening folders in a Nemo window as root works without creating any objects. Also there does not get the file ~/sudo_as_user_successful created, where alone the name sounds suspicious; I wonder how sudo can run successful without displaying any password request! As the level system has been declared as obsolete the update manager has lost its importance and gives at now nothing than trouble.

**Comment by CottonEaster** [comment]
@Cos-mo 

It might be an idea to ensure that you post a comment about this in the (or [a](https://blog.linuxmint.com/?p=3581#comments)) beta thread.

**Comment by kmkom** [comment]
I can confirm the error for Mint 19-Beta. And someone has already reported the bug in the announcement thread. There, no further comments were made...

I noticed it because my backup program for the Homer folder stopped at the.dbus folder (which has the wrong root privileges).

**Comment by CottonEaster** [comment]
Since this is a serious bug, I do hope it will get fixed. I do not feel like having to deal with it on my system!

**Comment by C4br1t0** [comment]
Hi!

First of all, please forgive my tbiott level english.

Allow me to point something that may or may not help. 

Sometimes I use to run nemo as root to fix some things (gksudo nemo) and I prefer to set nemo as double panel and list view from start, instead of default single panel and icon view, so I run as root and set it on preferences, but since LM18 (as far as i remember), nemo just can't save/retain the preferences. 

So I tried to run dconf-editor as root from terminal. No lucky.

After reading the comments here, I've tried changing the ./config/dconf/user ownership at terminal and tried to save preferences. Ownership returns to root. At dconf-editor, every action, every click, turn ownership to root.

So my guess is that it may not have to do with Update Manager, but something to do with running something with a gui on root mode. I said with a gui because it doesn't occurs if you run commands in pure terminal.

To test it, I ran xed as root (gksudo xed) and again  ./config/dconf/user ownership changed from "C4br1t0" to "root".

And what about Update Manager? Well, maybe it's because it is running as root or on root privilege?

Well, for me the problem isn't the ownership, but the effect of not allowing to save changes under root privileges.

I don't know if it can help...

**Comment by bigflipo** [comment]
Nice flag

**Comment by LinuxOnTheDesktop** [comment]
I have just now encountered this problem on Mint 19.1. Relevant info - apt output - is on Pastebin, [here](https://pastebin.com/uhnrQVHN).

@xenopeek : if I may: you've been _unassigned_ from this bug?

**Comment by xenopeek** [comment]
That's fine; see gm10 above doing the real work. I'm just helping with triaging.

**Comment by gm10** [comment]
There, if you feel better with someone assigned @LinuxOnTheDesktop. ;) My patch referenced above should take care of this should Clem go with it.
