### ISSUE TITLE
Kernel window doesn't known about lowlatency kernels

### ISSUE THREAD

**Issue by mxa** [linuxmint/mintupdate#200]
Somehow the Kernel window thinks a different Kernel is currently installed.
![kernel](https://cloud.githubusercontent.com/assets/1220707/21564252/a68f75c6-ce8b-11e6-8a64-d81147b5af86.png)

**Comment by clefebvre** [comment]
Hi,

What version of mintupdate? Can you reproduce the issue with version 5.2.1.1?

**Comment by mxa** [comment]
That's reproducible with version 5.2.1

**Comment by mxa** [comment]
and 5.2.9

**Comment by S-Marais** [comment]
and 5.3.2

**Comment by xenopeek** [comment]
mintupdate gets the current version from command `uname -r`. I can't reproduce the issue.

@mxa or @S-Marais if you can still reproduce the issue, please run the following two commands on the terminal and share the output:

`uname -r`

`/usr/lib/linuxmint/mintUpdate/checkKernels.py | sort -r`

**Comment by mxa** [comment]
```
$uname -r
4.14.14-041414-lowlatency
$ /usr/lib/linuxmint/mintUpdate/checkKernels.py | sort -rKERNEL###004.013.000.032.35~16.004.001###4.13.0-32###4.13.0-32.35~16.04.1###0###0###0###0###1
KERNEL###004.013.000.031.34~16.004.001###4.13.0-31###4.13.0-31.34~16.04.1###0###0###0###0###1
KERNEL###004.013.000.026.29~16.004.002###4.13.0-26###4.13.0-26.29~16.04.2###0###0###0###0###1
KERNEL###004.013.000.025.29~16.004.002###4.13.0-25###4.13.0-25.29~16.04.2###0###0###0###0###1
KERNEL###004.013.000.021.24~16.004.001###4.13.0-21###4.13.0-21.24~16.04.1###0###0###0###0###1
KERNEL###004.013.000.019.22~16.004.001###4.13.0-19###4.13.0-19.22~16.04.1###0###0###0###0###1
KERNEL###004.013.000.017.20~16.004.001###4.13.0-17###4.13.0-17.20~16.04.1###0###0###0###0###1
KERNEL###004.013.000.016.19~16.004.003###4.13.0-16###4.13.0-16.19~16.04.3###0###0###0###0###1
KERNEL###004.011.000.014.20~16.004.001###4.11.0-14###4.11.0-14.20~16.04.1###0###0###0###0###1
KERNEL###004.011.000.013.19~16.004.001###4.11.0-13###4.11.0-13.19~16.04.1###0###0###0###0###1
KERNEL###004.010.000.042.46~16.004.001###4.10.0-42###4.10.0-42.46~16.04.1###0###0###0###0###1
KERNEL###004.010.000.040.44~16.004.001###4.10.0-40###4.10.0-40.44~16.04.1###0###0###0###0###1
KERNEL###004.010.000.038.42~16.004.001###4.10.0-38###4.10.0-38.42~16.04.1###0###0###1###0###1
KERNEL###004.010.000.037.41~16.004.001###4.10.0-37###4.10.0-37.41~16.04.1###0###0###0###0###1
KERNEL###004.010.000.035.39~16.004.001###4.10.0-35###4.10.0-35.39~16.04.1###0###0###0###0###1
KERNEL###004.010.000.033.37~16.004.001###4.10.0-33###4.10.0-33.37~16.04.1###0###0###0###0###1
KERNEL###004.010.000.032.36~16.004.001###4.10.0-32###4.10.0-32.36~16.04.1###0###0###0###0###1
KERNEL###004.010.000.030.34~16.004.001###4.10.0-30###4.10.0-30.34~16.04.1###0###0###0###0###1
KERNEL###004.010.000.028.32~16.004.002###4.10.0-28###4.10.0-28.32~16.04.2###0###0###0###0###1
KERNEL###004.010.000.027.30~16.004.002###4.10.0-27###4.10.0-27.30~16.04.2###0###0###0###0###1
KERNEL###004.010.000.026.30~16.004.001###4.10.0-26###4.10.0-26.30~16.04.1###0###0###0###0###1
KERNEL###004.010.000.024.28~16.004.001###4.10.0-24###4.10.0-24.28~16.04.1###0###0###0###0###1
KERNEL###004.010.000.022.24~16.004.001###4.10.0-22###4.10.0-22.24~16.04.1###0###0###0###0###1
KERNEL###004.010.000.021.23~16.004.001###4.10.0-21###4.10.0-21.23~16.04.1###0###0###0###0###1
KERNEL###004.010.000.020.22~16.004.001###4.10.0-20###4.10.0-20.22~16.04.1###0###0###0###0###1
KERNEL###004.010.000.019.21~16.004.001###4.10.0-19###4.10.0-19.21~16.04.1###0###0###0###0###1
KERNEL###004.010.000.014.16~16.004.001###4.10.0-14###4.10.0-14.16~16.04.1###0###0###0###0###1
KERNEL###004.008.000.058.63~16.004.001###4.8.0-58###4.8.0-58.63~16.04.1###0###0###0###0###1
KERNEL###004.008.000.056.61~16.004.001###4.8.0-56###4.8.0-56.61~16.04.1###0###0###0###0###1
KERNEL###004.008.000.054.57~16.004.001###4.8.0-54###4.8.0-54.57~16.04.1###0###0###0###0###1
KERNEL###004.008.000.053.56~16.004.001###4.8.0-53###4.8.0-53.56~16.04.1###0###0###0###0###1
KERNEL###004.008.000.052.55~16.004.001###4.8.0-52###4.8.0-52.55~16.04.1###0###0###0###0###1
KERNEL###004.008.000.051.54~16.004.001###4.8.0-51###4.8.0-51.54~16.04.1###0###0###0###0###1
KERNEL###004.008.000.049.52~16.004.001###4.8.0-49###4.8.0-49.52~16.04.1###0###0###0###0###1
KERNEL###004.008.000.046.49~16.004.001###4.8.0-46###4.8.0-46.49~16.04.1###0###0###0###0###1
KERNEL###004.008.000.045.48~16.004.001###4.8.0-45###4.8.0-45.48~16.04.1###0###0###0###0###1
KERNEL###004.008.000.044.47~16.004.001###4.8.0-44###4.8.0-44.47~16.04.1###0###0###0###0###1
KERNEL###004.008.000.042.45~16.004.001###4.8.0-42###4.8.0-42.45~16.04.1###0###0###0###0###1
KERNEL###004.008.000.041.44~16.004.001###4.8.0-41###4.8.0-41.44~16.04.1###0###0###0###0###1
KERNEL###004.008.000.039.42~16.004.001###4.8.0-39###4.8.0-39.42~16.04.1###0###0###0###0###1
KERNEL###004.008.000.036.36~16.004.001###4.8.0-36###4.8.0-36.36~16.04.1###0###0###0###0###1
KERNEL###004.008.000.034.36~16.004.001###4.8.0-34###4.8.0-34.36~16.04.1###0###0###0###0###1
KERNEL###004.004.000.112.135###4.4.0-112###4.4.0-112.135###0###0###0###1###1
KERNEL###004.004.000.109.132###4.4.0-109###4.4.0-109.132###0###0###0###0###1
KERNEL###004.004.000.108.131###4.4.0-108###4.4.0-108.131###0###0###0###0###1
KERNEL###004.004.000.104.127###4.4.0-104###4.4.0-104.127###0###0###0###0###1
KERNEL###004.004.000.103.126###4.4.0-103###4.4.0-103.126###0###0###0###0###1
KERNEL###004.004.000.101.124###4.4.0-101###4.4.0-101.124###0###0###0###0###1
KERNEL###004.004.000.098.121###4.4.0-98###4.4.0-98.121###0###0###0###0###1
KERNEL###004.004.000.097.120###4.4.0-97###4.4.0-97.120###0###0###0###0###1
KERNEL###004.004.000.096.119###4.4.0-96###4.4.0-96.119###0###0###0###0###1
KERNEL###004.004.000.093.116###4.4.0-93###4.4.0-93.116###0###0###0###0###1
KERNEL###004.004.000.092.115###4.4.0-92###4.4.0-92.115###0###0###0###0###1
KERNEL###004.004.000.091.114###4.4.0-91###4.4.0-91.114###0###0###0###0###1
KERNEL###004.004.000.089.112###4.4.0-89###4.4.0-89.112###0###0###0###0###1
KERNEL###004.004.000.087.110###4.4.0-87###4.4.0-87.110###0###0###0###0###1
KERNEL###004.004.000.083.106###4.4.0-83###4.4.0-83.106###0###0###0###0###1
KERNEL###004.004.000.081.104###4.4.0-81###4.4.0-81.104###0###0###0###0###1
KERNEL###004.004.000.079.100###4.4.0-79###4.4.0-79.100###0###0###0###0###1
KERNEL###004.004.000.078.099###4.4.0-78###4.4.0-78.99###0###0###0###0###1
KERNEL###004.004.000.077.098###4.4.0-77###4.4.0-77.98###0###0###0###0###1
KERNEL###004.004.000.075.096###4.4.0-75###4.4.0-75.96###0###0###0###0###1
KERNEL###004.004.000.072.093###4.4.0-72###4.4.0-72.93###0###0###0###0###1
KERNEL###004.004.000.071.092###4.4.0-71###4.4.0-71.92###0###0###0###0###1
KERNEL###004.004.000.070.091###4.4.0-70###4.4.0-70.91###0###0###0###0###1
KERNEL###004.004.000.067.088###4.4.0-67###4.4.0-67.88###0###0###0###0###1
KERNEL###004.004.000.066.087###4.4.0-66###4.4.0-66.87###0###0###0###0###1
KERNEL###004.004.000.064.085###4.4.0-64###4.4.0-64.85###0###0###0###0###1
KERNEL###004.004.000.063.084###4.4.0-63###4.4.0-63.84###0###0###0###0###1
KERNEL###004.004.000.062.083###4.4.0-62###4.4.0-62.83###0###0###0###0###1
KERNEL###004.004.000.059.080###4.4.0-59###4.4.0-59.80###0###0###0###0###1
KERNEL###004.004.000.057.078###4.4.0-57###4.4.0-57.78###0###0###0###0###1
KERNEL###004.004.000.053.074###4.4.0-53###4.4.0-53.74###0###0###0###0###1
KERNEL###004.004.000.051.072###4.4.0-51###4.4.0-51.72###0###0###0###0###1
KERNEL###004.004.000.047.068###4.4.0-47###4.4.0-47.68###0###0###0###0###1
KERNEL###004.004.000.045.066###4.4.0-45###4.4.0-45.66###0###0###0###0###1
KERNEL###004.004.000.043.063###4.4.0-43###4.4.0-43.63###0###0###0###0###1
KERNEL###004.004.000.042.062###4.4.0-42###4.4.0-42.62###0###0###0###0###1
KERNEL###004.004.000.038.057###4.4.0-38###4.4.0-38.57###0###0###0###0###1
KERNEL###004.004.000.036.055###4.4.0-36###4.4.0-36.55###0###0###0###0###1
KERNEL###004.004.000.034.053###4.4.0-34###4.4.0-34.53###0###0###0###0###1
KERNEL###004.004.000.031.050###4.4.0-31###4.4.0-31.50###0###0###0###0###1
KERNEL###004.004.000.028.047###4.4.0-28###4.4.0-28.47###0###0###0###0###1
KERNEL###004.004.000.024.043###4.4.0-24###4.4.0-24.43###0###0###0###0###1
KERNEL###004.004.000.022.040###4.4.0-22###4.4.0-22.40###0###0###0###0###1
KERNEL###004.004.000.021.037###4.4.0-21###4.4.0-21.37###0###0###0###0###1

```

![screenshot from 2018-01-26 13-57-58](https://user-images.githubusercontent.com/1220707/35440762-1aff8974-02a1-11e8-9d23-3e3be149f55f.png)

**Comment by xenopeek** [comment]
Kernel "3.13.0-37-generic" is the default text in the kernel window https://github.com/linuxmint/mintupdate/blob/master/usr/share/linuxmint/mintupdate/kernels.ui#L239. This means none of the kernels returned by checkKernels.py are currently used and your output confirms that.

It appears checkKernels.py specifically excludes **lowlatency** kernels https://github.com/linuxmint/mintupdate/blob/master/usr/lib/linuxmint/mintUpdate/checkKernels.py#L33. I don't know yet how to proceed on this.

Thanks for the quick response @mxa!

**Comment by ewangi** [comment]
As an outsider, I would have thought that at a minimum the default text "Kernel 3.13.0-37-generic currently loaded" should be removed since it is incorrect and misleading.

Better, if the active kernel is not one covered by checkKernels.py then the text should read something like "Kernel 4.14.14-041414-lowlatency currently loaded (Note that this kernel is not included in the kernels handled by Update Manager)".

Best, checkKernels.py should be modified to include low latency (and other, if relevant) kernels. It's the solution that most closely reflects reality.

**Comment by S-Marais** [comment]
so the problem here is that checkKernels.py looks for linux-image-*-generic only
`current_version = subprocess.check_output("uname -r", shell = True).decode("utf-8").replace("-generic", "").strip()`

adding .replace("-lowlatency", "") before .slpit() kinda solves the kernel recognition even if it doesn't show the lowlatency extension but at least it shows the proper version.

I still need to dig further to find how I can get rid of the kernel update for the version already installed.

**Comment by S-Marais** [comment]
@xenopeek also we are not here talking about providing users a way to update kernel through the mintUpdate application. The reason was and still is that low latency kernels are not used by a lot of people. Since the goal of the distribution is to make things easy for a huge amount of people, adding a complexicity level into the application is unwise.
On the other hand, displaying proper informations about a computer is wise. Displaying a default generic kernel that is long gone from Linux Mint kernel list is not a good thing. I'd rather have a message saying that the kernel actually used is not managed by the application than have a false version displayed.

**Comment by DanielRios549** [comment]
I make a modification in the source code, the only thing needed to mintUpdate works with lowlatency kernels, is editing a variable, no changes to interface, I think this is the best way to make mintUpdate compatible with lowlatency kernels, the only problem is to remove generic ones already installed, either it works with generic or with lowlatency ones, so the only way to remove them is using synaptic. I already make tests installing and removing other versions, all right up to now, but I will wait for kernel updates to make sure it will work property. If there will no problems, I will make a pull request. What do you think?

**Comment by S-Marais** [comment]
you can test it right now by installing an older kernel and by purging the most recents ones. Let's say installing 4.13.0-36 and removing 4.13.0-37 and you get a notification update. Keep in mind that the goal here is for lowlatency users to have properly displayed information about their kernel and to not be notified of a version update for a 4.13.0-37-generic when you have 4.13.0-37-lowlatency installed.
We are not looking to modify the goal of the updater which is to make things simple for a wide number of people. introducing a new layer of kernel would make things a lot more confusing for people that are not really aware of what they are doing.

**Comment by DanielRios549** [comment]
Good idea, I will test this, but the installation and purge are work property for manual installation on kernel window. And get me a question, the packages prefixed with "linux-image-extra" are only for generic ones, right? I removed them from lowlatency ones because I didn't find them on Synaptic, only for generic ones, but I kept them with generic configuration

**Comment by DanielRios549** [comment]
The updater are identical by default, thais is, when are using generic kernels. The only difference is that when they are using lowlatency ones, nothing is made with generic ones, install or purge, nothing. So, if I have 4.13.0-37-generic installed, and switch to lowlatency mode, the updater will not show it as installed or active, because it doesn't work with generic ones in lowlatency mode and vice versa. This is only for people who really want to use lowlatency kernels, not for everybody. The only problem is that, my system are not showing update for lowlatency kernel, meanwhile, the updater also does not, Synaptic and even sudo apt update, nothing is showing that a update from 4.13.0-36-lowlatency to 4.13.0-37-lowlatency is available. What do I have to do? Its a configuration or a problem?

**Comment by minto0s** [comment]
Not realizing that there was a discussion under way I created a new issue earlier about the same topic aka low latency and wrong kernel info on update manager if low latency kernel is installed. I am also noticing that this issue has been around for quite a while.
Frankly I didn't read the nitty gritty of the discussion as I am in a rush to move to something else and I didn't want to drop this issue.
The point that I want to highlight is that it would be beneficial to some to be able to install both the generic and low latency versions of a given kernel in the same shot. Simply because there are some applications that perform a bit better with low latency and if one knows that such a software will be used during the session one might elect to start the low latency kernel as opposed to the generic.
In any event it would be nice to get this matter addressed one way or another. But as a minimum the wrong kernel version identification should be addressed immediately even if it means that there will be no kernel version info up on the top of the kernel window. It is dangerous to flash the wrong version and mislead the operator of the system. My two cents.

**Comment by DanielRios549** [comment]
I will make a change to the mintUpdate works with both generic and lowlatency, but do you think the best is only when the user change to lowlatency, to doesn't add complexity in the program, or do you think permanently is better?

**Comment by S-Marais** [comment]
@DanielRios549 keep the goal of the updater: keep things simple. If someone needs lowlatency and has it installed then (maybe) tell this specific person if there is an upgrade available. But since 80-85% of people are not using lowlatency I would not make it permanent.
At the minimum we are looking to get proper info form the updater (which kernel is installed) and no message that we have an upgrade available when for instance we have a 4.13.0-37-lowlatency installed but the updater still offers the 4.13.0-37-generic update. We want that out.

**Comment by minto0s** [comment]
@DanielRios549: The "Kernels" window under "Update Manager" (Update Manager > View > Linux Kernel) doesn't show any update availability information. Update availability is dealt with in Update Manager's main window if there is an update for the currently installed kernel, provided that that kernel is coming from Linux Mint's own repository.
On the other hand, if an ubuntu kernel is manually installed (dpkg -i linux-headers*.deb linux-image*.deb), it nicely shows up in the "Kernels" window within the proper version category IF it is a generic type. Actually, currently there is no info about the type, only generic kernels show up, any low-latency simply get ignored by "Kernels" window. So, my suggestion, next to the available kernel type kernel simply indicate whether it is generic or low-latency, and ALLOW low-latency material to show up (regardless whether it is installed from Linux Mints own repository or from ubuntu mainline kernel repos). And whichever is active is further labeled as "Active" and those installed on the system are all labeled as "Installed" (as it is right now with the current logic).
Frankly, I have no opinion about how to deal with suggesting that there is a newer version of the installed kernel and the update from the main Update Manager window, simply because I do not do it that way (and frankly I find it dangerous to update the kernel in the vacuum along with other system or user level software updates). 
If I had to put in my two cents, I would suggest that kernel upgrading should be moved entirely to the Kernel window and nothing about kernels should be left in the main window. But that might be deep surgery and I do not want to make things more complicated.
Thanks for reading.

**Comment by xenopeek** [comment]
Let's do one thing at a time. Let's first implement that the kernel window always shows the active kernel version regardless of its origin or build (generic or low-latency). That solves the original issue.

This goes further than the lowlatency build BTW as there are a bunch of other kernel builds in the package base (I spotted -azure, -azure-edge, -gcp and -oem on https://packages.ubuntu.com/search?suite=xenial&arch=amd64&searchon=names&keywords=linux-image-4).

One possible approach:

- Alter https://github.com/linuxmint/mintupdate/blob/master/usr/lib/linuxmint/mintUpdate/checkKernels.py to detect when the active kernel doesn't end with -generic
- Then either:
  - Only respond the active kernel back
  - Or respond back all the -generic kernels are per normal but add the active kernel (non -generic) to the list

**Comment by minto0s** [comment]
@xenopeek: It's probably fair to limit kernel types to generic and low latency (and maybe virtual) as these are probably the only ones used in a desktop environment, The rest seem to be for cloud based systems or servers.
I agree that the first thing to fix is the correct detection and display of the active kernel version on top of the kernels window including the low latency ones. But, if that is done without at least flagging the kernel types in the kernel listing it will be very confusing if both generic and low latency kernels of the same version are installed. Right now that list only shows kernel version class and within each all the available versions with no mention of type.

**Comment by xenopeek** [comment]
https://github.com/linuxmint/mintupdate/commit/bbb50cf2e06397b9d2bbaad6cfa22fed20369253 implements support for lowlatency kernels in mintupdate. It is currently implemented as an advanced feature. To enable mintupdate to use lowlatency kernels run this on Linux Mint 19:

`gsettings set com.linuxmint.updates use-lowlatency-kernels "true"`

**Comment by tester2011** [comment]
Hmm... Just came across this thread. I'm having similar issues since upgrading to MintUpdate 5.3.2.3.

However, NOT just low-latency Kernels...

I run Linux Mint 18.3 xfce 64-bit and use Ukuu to installl the latest Linux Kernels on my system. 

Currently running 4.16.8 generic

"uname -r" shows: 4.16.8-041608-generic. 

Ukuu also shows that 4.16.8 is currently running, however the View>Linux kernels menu in MintUpdate shows that no kernels are currently installed (under the various 4.x sub-headings). Underneath the "Kernels" window-title, its displays the text: "Kernel 3.13.0-37-generic currently loaded"

Clearly something's not right. Any additional information required?

Cheers,

Mike.

**Comment by xenopeek** [comment]
Can you make this into a new issue? It may likely be related as you suggest but to not mix discussions and analysis done, better to make a new issue and refer to this one.

**Comment by tester2011** [comment]
@xenopeek,

Apologies - yes, I started a new issue, as requested.

Cheers,

Mike.
