### ISSUE TITLE
If Synaptic currently running, error message is unclear

### ISSUE THREAD

**Issue by dg1727** [linuxmint/mintupdate#204]
See also #134 

Issue can be duplicated as follows:  

1.  Open Synaptic 
2.  Open mintUpdate and click Refresh 
3.  A dialog appears saying:  
**`Another synaptic is running`**
`There is another synaptic running in interactive mode. Please close it first.`

The word "another" implies that mintUpdate is Synaptic.  Something like the following might be better:  
`Another package manager (Synaptic running in interactive mode) is accessing the package database.`
`Please close that other package manager first.`

The phrase in () may, in the future, have something else filled in if that other package manager isn't Synaptic (it may be `apt-get`, `aptitude`, etc.).  

On the command line, the PID of the other package manager can be obtained with:  
`THATPID=$(fuser /var/lib/dpkg/lock 2>/dev/null); echo $THATPID`

... and the executable's location and the name of the invoking user can be obtained with:
`ps -p $THATPID -o command=,user=`
... which may need to be refined for usage in source code (e.g., if either the executable name or the invoking username contains a space, then the output of that `ps` command line shouldn't be parsed by splitting on spaces).  

Anyway, if this dialog is indeed in Synaptic, then maybe a request can be made to that project to reword the dialog for when Synaptic is being used non-interactively by other GUI tools (mintUpdate in this case).

**Comment by ACinnamonUserInUK** [comment]
A similar problem can be seen (/reproduced) as follows.

1. Mint Update shows - perhaps just via its panel icon - some update(s) available.
2. Open terminal and run `sudo apt-get update && sudo apt-get upgrade` and install some update.
3. Open Mint Update and try to install updates. Result: 'Could not install the updates'. (See screenshot.)

![image](https://cloud.githubusercontent.com/assets/9998846/23048679/5ef38dde-f4af-11e6-81bb-9ef95aee3d55.png)

Suggested improvement: check whether updates were installed already or not; if they were, say something to that effect instead of, 'Could not install'.

**Comment by NikoKrause** [comment]
@dg1727 
Those strings are coded in synaptic itself and not in mintupdate:
https://github.com/linuxmint/synaptic/blob/master/po/synaptic.pot#L1103-L1116

**Comment by ACinnamonUserInUK** [comment]
I may have muddied things here by adding my somewhat different complaint to the original posters. It seems that NikoKrause's response is to dg1727's complaint, and not mine. Should I try to delete my comment and resurrect it as a separate thread (/issue)?
