### ISSUE TITLE
Descriptions are sometimes taken from inappropriate package in multi-package update

### ISSUE THREAD

**Issue by dg1727** [linuxmint/mintupdate#207]
mintUpdate 5.2.0 on LMDE2

Using the following in /etc/apt/sources.list.d/
`deb http://mirrorservice.org/sites/ftp.debian.org/debian/ jessie-backports main contrib non-free`

mintUpdate, for both the short description & long description of the "libreoffice" update, uses the descriptions of the "ure" package, and these descriptions don't fit the "libreoffice" update in general.  

Maybe the descriptions should be taken from an APT package whose name begins with the displayed name, if any such APT package exists in the update (the displayed name in this case is "libreoffice").  

The same (or a similar) issue appears to affect the "firmware-nonfree" Linux Mint update.

**Comment by dg1727** [comment]
Presumably each Linux Mint update is really "one APT package plus that package's dependencies that are at a new version in the repo."  If so, then probably you could just use the short & long description from that one package.

**Comment by xenopeek** [comment]
Confirming this as a general issue for packages built from the same source package. For example updates for the source package glibc show as short and long description the text from the locales package. Example screenshot from Linux Mint 18.1 (but confirmed on 18.2 as well).

![Screenshot](https://forums.linuxmint.com/download/file.php?id=35124&mode=view)

Note that changelogs are displayed correctly. That's because source packages have changelogs. But source packages don't have a description. Update Manager somehow selects one of the packages in the update set to use for description? See source package glibc https://packages.ubuntu.com/source/xenial/glibc. Changelogs but no description.

**Comment by gm10** [comment]
I don't think there is a good solution to this other than showing the descriptions of all packages included in an update, if different, along with the packages they belong to. This does however risk causing more confusion than it solves. 

Trying to find a common prefix instead as suggested by @dg1727 in the referenced issue that I closed may sound interesting at face value but there is no guarantee that such a commonality exists and thus that cannot be the way.
