### ISSUE TITLE
"IMPORTANCE" instead of "LEVEL"

### ISSUE THREAD

**Issue by RBM-GITHUB** [linuxmint/mintupdate#251]
When I open the updater, it shows me the list of programs in order of the "level". What does it mean? After spending some time, I concluded it means "how important this program is to the computer" but I'm still not sure.

So, could you rename the label from "LEVEL" to "IMPORTANCE" or "SECURITY IMPACT" or something like that? Thanks a lot!

**Comment by NikoKrause** [comment]
Which Linux Mint version do you use? Since Linux Mint 18.2 there is a help page in mintupdate, which explains in detail, what the "levels" mean (https://github.com/linuxmint/mintupdate/blob/master/usr/share/help/C/mintupdate/levels.page)

If you don't use 18.2 yet, then here's the site, explaining levels, in a more readable form: https://pastebin.com/raw/knBXBJSW

**Comment by RBM-GITHUB** [comment]
Thank you for a quick reply! So that's indicating the *probability of running into problems after applying those updates*, right? Sorry unfortunately I switched to Windows after heating up my laptop and lagging videos due to Intel Graphics not being really as "efficient" somehow as Windows is... But I think I was using that version, 18.2. Yes. And I did not know there was a manual page (lol).

I suggested this idea because I thought labeling it just "LEVEL" didn't seem obvious to me. I mean, I had to think "what does it mean?" for a second. I know Mint is like the most popular distro by now, so why not make things as obvious and self-explanatory so I don't have to read the manual (I'm an absolute beginner)?
