### ISSUE TITLE
Cat-friendly mintupdate

### ISSUE THREAD

**Issue by Schallaven** [linuxmint/mintupdate#253]
Hello all!

Let me start this post by saying how much I like Mint, the community around it, and the effort of the team. I appreciate the goals and aims of Mint, which made me want to contribute to further these goals.

Therefore, in the last two weeks I spend some time to restructure and rewrite a great part of the mintupdate code (a lot of Spaghetti code and copy&paste blocks) to improve it. For instance, I put the menu code in an own UI file, splitted the code into several .py files (one for each class), cleaned and removed branches which were never reached/used, etc. I added a lot of comments (I know Joseph hates them :wink:  ).

While there is still a lot to do, I think the current version is already much better to read and especially maintain. Since it is still a work in progress, I put it in an own repo *catmintupdate*, you can find [here](https://github.com/Schallaven/catmintupdate). Take a look and compare!

Along the way, I managed to fix some bugs and implement some things, which were requested from users (e.g. the install-size/on-disk-size column).

Also, with some help from very nice linuxadvocates on spotchat, I implemented another assessment (level) system than the current. Instead of 5 levels, which mostly lead to confusing among users:

```
<Guest12345> guys, i'm new to linux, can you tell me why level4-5 updates are marked as dangerous? if there's an exploit in the kernel and lvl4-5 updates are disabled, how do you secure the OS?
...
<Guest67890> what's the difference between lvl1&2? Is it safe to install lvl3 updates?
```

there are now only 3 (actually just two + not assessed) levels: fine-to-install, caution-core-component-affected, and not-assessed. Instead of numbers, we use in our opinion more descriptive emoticons:

![bildschirmfoto zu 2017-06-20_01-36-29](https://user-images.githubusercontent.com/6428497/27364783-973ab0ca-560a-11e7-952a-49e8445f88f9.png)

(There is an additional icon for PPA sources, which is not shown.)

Additionally, we improved the GUI to get more information in a more straightforward way. Instead of hiding the level-description in a help-file, we show the respective symbols in the description box. The description of the icons is complemented by some extra strings for security updates or from the assessment file (former rules file) to help the user understand **why** something was assessed in a certain way.

Last but not least, there are some other nice visual improvements such as the highlighting of version-string-differences, which are certainly useful for mintupdate.

It should be noted that in accordance to the KISS principle, I removed the ability to administrate and update the kernel with *catmintupdate*. I think an extra, more sophisticated tool placed in the control-center can and should handle this important task in the future. I might start one in the next weeks.

So, why *catmintupdate*? Well, because of (and yes it is animated!):

![bildschirmfoto zu 2017-06-20_02-16-42](https://user-images.githubusercontent.com/6428497/27364796-a98da9e4-560a-11e7-941f-0af1b474eb93.png)

More screenshots and information can be found at [the catmintupdate repository](https://github.com/Schallaven/catmintupdate).

I hope that some of these useful features and maybe some of the code improvements will find its way into *mintupdate* :smile: 

Cheers,
Schallaven

**Comment by JosephMcc** [comment]
Ok. Since you posted this here I assume feedback is ok.

First off I don't hate comments :) I hate pointless commenting. Example:
```
# return string
return my_string
```
That's silly and you have way too much of that.

Not a fan of the level icon things.

The highlighting of stuff just looks weird and it will break depending on the theme that's being used. Resulting in cases where you won't be able to read it.

The whole cat theme is just silly.

**Comment by Piiit** [comment]
Just had a short look at your screenshots. 

I wanna say that I like:
- The level icons for level 1 and level 2 updates, the red hand means "no-go" for me, and shouldn't be used. 
- The additional "type and level assessment" description inside the description tab are also nice, giving some additional information to regular users (maybe the text could be revised). 

However, what I don't like is:
- the cat animation, since it is not compliant to any other part of cinnamon (and doesn't look "professional" to me)
- the removing of kernel update feature (since update is what this tool is for)
- the highlighting of version numbers (to much for such a little information gain)

From the coding part, I haven't had a look... 
However, IMHO comments should only describe why some code has been written and not how (except if it is very complicated)... and they should only be in places which are not self-explanatory.

Maybe, if you could just focus on a single additional feature and provide a PR (or discussion) for that? My favorite would be the "type and level assessment description", or the ability to read the changelogs after installation processes had already been started.

Cheers.

**Comment by NikoKrause** [comment]
I don't like the emojis. And the cat. It looks too playful. Like a minesweeper game.

But I like the description of the icons.

And actually I like the highlighting of the version difference. But JosephMcc has a point, that it will cause theme issues.

**Comment by xenopeek** [comment]
The install-size/on-disk-size column feature request is still open for Linux Mint 19. A separate PR for that would be welcome.
