### ISSUE TITLE
Password is queried in terminal rather than UI for mintupdate

### ISSUE THREAD

**Issue by Cypher1** [linuxmint/mintupdate#258]
I'm having the same issue as described here: https://www.reddit.com/r/linuxmint/comments/2tt85o/why_is_mintupdate_trying_to_authenticate_to_gain/

I'm running i3 on linux-mint cinnamon. I'd love to find a solution e.g. using gksudo etc.

**Comment by xenopeek** [comment]
This would probably have better been posted on the forums. In any case, mintupdate on Linux Mint 19 uses Polkit's pkexec instead of gksudo. Should you also have this question for Linux Mint 19, there is a [host of options](https://wiki.archlinux.org/index.php/Polkit#Authentication_agents) for graphical Polkit authentication agents. pkexec will fall back on a textual authentication agent if none of those are running in your session.

**Comment by Cypher1** [comment]
Please correct me if I'm wrong but pkexec doesn't seem to be installed by default (otherwise I wouldn't have had this issue).

I believe that this is broken (if it doesn't work with the graphical sudo UI that is provided by default) and should be fixed (either to use gksudo or to use which ever is installed).
