### ISSUE TITLE
Update Manager offers me an update to a kernel I've uninstalled

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/mintupdate#269]
Please see screenshots. Perhaps this behaviour is intended but I imagine that it is not.

![image](https://user-images.githubusercontent.com/9998846/28935037-a7fecd4e-7872-11e7-83d0-9a3e4f7cc923.png)

![image](https://user-images.githubusercontent.com/9998846/28935072-c9dfb4aa-7872-11e7-9c9f-abd38e75e47a.png)

![image](https://user-images.githubusercontent.com/9998846/28935114-f0ac5dcc-7872-11e7-8307-be207600c510.png)

Mint 18.2 Cinnamon.

**Comment by xenopeek** [comment]
You can look in the description tab what the actual package is that is included in that update. Multiple packages are built from the kernel source and Update Manager shows these as one update under the name of the source package. You can see from the size of 112KB that this isn't actual a kernel. It will be some other component.

That may either be installed because it is needed (the component is not available from a higher kernel source version) or because you have another (meta) package installed that depends on this specific version.
