### ISSUE TITLE
Apt-cache corrupted message could be more helpful

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/mintupdate#284]
I found the following error message unhelpful. For, I reacted by searching MintUpdate's various menus, trying to find the window that changed the mirrors. Having failed in that, I then clicked 'OK' on the error window, only to find that so doing took me to the windows I wanted.

![image](https://user-images.githubusercontent.com/9998846/32417238-42f749a0-c24e-11e7-93b5-097358a3cbac.png)

**Comment by LinuxOnTheDesktop** [comment]
Just now I encountered the corruption message. I did so after, and perhaps because, I have used Software Sources to do maintenance, had been prompted to reload the cache, and had not done so. I found that, after a `sudo apt update`, _mintupdate worked normally_. So _seemingly the advice to switch to a different mirror_ - and Mint 22.1 retains that advice - _is not always good advice_.
