### ISSUE TITLE
Uninstalled kernel listed in updates even though preferences are that it shouldn't be shown

### ISSUE THREAD

**Issue by rmwiseman** [linuxmint/mintupdate#302]
I tried upgrading my kernel (to 4.13.0), found it didn't work, booted successfully with the previous kernel (4.10.0) and uninstalled the new kernel.  My Update Manager preferences are to only show levels 1 & 2, but the new kernel (4.13.0) is still listed despite being a level 4 update.

**Comment by rmwiseman** [comment]
I've since updated the kernel because of the meltdown and spectre fixes, and am now on 4.4.0-109-generic.  My update manager's settings are still that only levels 1 and 2 should be visible and selected; all other levels should neither be visible nor selected.  But I'm currently seeing a level 4 kernel update:

![image](https://user-images.githubusercontent.com/10866705/35268045-fa95f958-001f-11e8-9594-d73de0a1af98.png)

So the problem persists even when I'm on a different kernel and haven't already installed [and uninstalled] the one being offered.

**Comment by xenopeek** [comment]
There are a number of reasons why it's shown:

- It is a security update. Those are shown regardless of how you've configured levels because you should always see security updates. See your update policy.
- And your active kernel must still be 4.10. That one is the old and no longer supported HWE (hardware enablement) kernel. It is thus to be replaced by 4.13 as that is the current HWE kernel. The non-HWE kernel is 4.4 and that one was your active kernel you wouldn't be offered to upgrade to 4.13.

Mind that your boot manager by default boots the kernel version with the highest release and version number. So if you have 4.10 and 4.4 installed, by default you'd boot 4.10.

Open View > Linux kernels from Update Manager's menu. What does it say is your current kernel? If it is not in the 4.4 release and you do want to use the 4.4 release, hold down Shift key during boot to make the GRUB boot menu appear and use that to select an older kernel release for booting.

**Comment by rmwiseman** [comment]
Thanks for the information @xenopeek.  My current kernel is 4.4.0-112, which is the highest version number I have got installed.  I was previously on a 4.10 kernel but changed to 4.4 after reading [advice in the recent blog entry and discussion about Meltdown/Spectre](https://blog.linuxmint.com/?p=3496#comment-139670).  (The 4.13 kernel does not work on my laptop: it gives me a black screen instead of a login screen.)
