### ISSUE TITLE
[feature request] Ability to set maximum number of kernels

### ISSUE THREAD

**Issue by ewangi** [linuxmint/mintupdate#309]
Request: The ability to specify a maximum number of kernels to be installed on the system. Any installation of a new kernel which pushes the number of installed kernels over this maximum will automatically purge the kernel installed on the system with the smallest version number. Suitable checks could be incorporated e.g. asking if the user wants to purge the particular version and requesting confirmation.

Rationale: For those who have the habit of installing the latest kernel versions (important, for example, with the versions currently coming through the pipe due to Meltdown and Spectre), the number of kernel versions installed on a system can quickly mount up. There have been several problems reported on LinuxQuestions of users whose /boot partitions have run out of space as a result. One strategy is to maintain a fixed number of kernels on the system e.g. the latest 3 kernels. This currently entails the manual purging of a kernel each time that a new one is installed. Providing automation of this process would make it easier.

**Comment by kneekoo** [comment]
> Suitable checks could be incorporated e.g. asking if the user wants to purge the particular version and requesting confirmation.

As long as we can instruct the update manager how many kernels we want to keep, I think there would be no need to ask the users the permission to purge the old ones because it would require an extra action regardless of our decision.

The automated kernel removal issue could be presented in a passive manner, as a warning on top of the update manager, just as we see the one about switching to a local mirror. The user would be informed about what happens, and they can click a button to go to the kernel update settings, which could allow us to set:
- how many kernels (in total) should be kept **OR**;
- how many kernels (per release) should be kept, just in case the user requires multiple versions for any reason;
- maybe allow the users to pin certain versions/releases, to prevent their automated removal;
- etc.

**Comment by gm10** [comment]
The next release will incorporate automation for automatic removal of no longer needed packages and that includes kernels. The specific number of kernels cannot be configured, it'll be between 2-4 depending on when the removal process runs.

Closing this for now.
