### ISSUE TITLE
linux mint 18.3 , mintupdate 5.3.2 error update , can't update list  

### ISSUE THREAD

**Issue by cappelikan** [linuxmint/mintupdate#322]
02.22@21:10 ++ Launching mintUpdate 
02.22@21:10 ++ Starting refresh 
02.22@21:10 ++ Initial refresh will happen in 10 minutes, 0 hours and 0 days 
02.22@21:10 -- Exception occurred in the refresh thread: <class 'subprocess.CalledProcessError'>

**Comment by xenopeek** [comment]
Hi, this doesn't have enough information to take action on. Please go through troubleshooting (see our guide https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/) and take help from the support forum to find the cause of your issue. Why I ask you to do that is explained in the guide. If the responsible component turns out to the be mintupdate you can comment here and I'll reopen.
