### ISSUE TITLE
could not refresh the list of updates

### ISSUE THREAD

**Issue by slavicd** [linuxmint/mintupdate#337]
Upon clicking on "Refresh" the result is always "Could not refresh the list of updates". Tried reinstalling mintupdate. apt-get update works without warnings.

Installed version: 5.3.2.1

![screenshot from 2018-04-02 20-05-13](https://user-images.githubusercontent.com/1071705/38227573-ac4bbac4-36b3-11e8-8a69-93811caaaef2.png)

**Comment by xenopeek** [comment]
This sounds like a problem with one of your configured repositories and not a bug in mintupdate. To get support with such issues please post a new topic on the forums https://forums.linuxmint.com/. See our [troubleshooting guide](http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/) for why. You should ideally include the output of the commands `inxi -Sr` and `apt update` run from the terminal in your topic on the forums, so that you can get the most immediate help.

**Comment by slavicd** [comment]
If you just checked the very forum you indicated before closing the issue, you'd notice that there already is a report just like mine, which nobody has solved so far. This sounds like a issue with mintupdate to me. 

https://forums.linuxmint.com/viewtopic.php?f=47&t=267166

Recommending you open the issue back.

**Comment by xenopeek** [comment]
That topic was solved with these steps: https://forums.linuxmint.com/viewtopic.php?f=47&t=267166#p1454336. Cause for that user was held packages.

**Comment by Allan-RB** [comment]
I have stumbled on a workaround that might shed some light on the problem.
If I start mintupdate from the session manager, or from the desktop menu, I get exactly this behaviour:
any attempt to refresh fails and the shield in the system tray turns red.
Running mintupdate from the terminal behaves the same way.

However, if I run mintupdate-launcher from a terminal, it behaves differently.
When I press the refresh button, I get a prompt in the terminal where mintupdate-launcher is running,
saying:
[sudo] password for <username>:
Type my password and, hey presto! The refresh works and I can update.
I get a GUI prompt for my password (to run Synaptic) when updating packages.
Looks like a problem with the GUI password prompt at the refresh stage, and the failure to update is being caused by a failure to authenticate.
