### ISSUE TITLE
Warn about updates requiring more storage than available

### ISSUE THREAD

**Issue by kneekoo** [linuxmint/mintupdate#347]
This should be prevented by checking the available space and warning the user in advance.
![lmde2-update-manager-no-space-left-on-device](https://user-images.githubusercontent.com/566306/38643025-296ea9ba-3ddc-11e8-859e-aab6e93bcd83.png)

A dedicated cleanup tool would be great to perform a few operations with a click:
- apt autoclean;
- old kernels removal (at least until #309 gets implemented);
- present a list of the top X programs sorted by the used space, so we can remove the ones we don't need (multiple selection required);
- present a button to the Disk Usage Analyzer **IF** the /home directory is installed on the same partition as root (/);
- etc.

**Comment by Magissia** [comment]
"present a button to the Disk Usage Analyzer IF the /home directory is installed on the same partition as root (/);" 
That would require to understand btrfq quotas and subvolumes to work properly.

**Comment by kneekoo** [comment]
Not every feature would supposed to be supported in the first release of such a program, just like not all file systems would have to be supported if this feature would be implemented. There's always room for improvement in the future.

**Comment by gm10** [comment]
Automatic download cache cleaning is now the default in all Mint releases, regular autoremoval of packages and old kernels will become an option in 19.2, but further disk cleanup options are outside of the scope of mintupdate and should be left to dedicated solutions. 

I'll consider the free space check as part of https://github.com/linuxmint/mintupdate/issues/206 but due to some updates requiring arbitrary amounts of temporary space (e.g. kernel updates with dynamic driver compilation via DKMS) this is hard to get right, and as your own screenshot shows, there's already a generic warning when your partition's free space falls below a certain percentage.

Closing this.

**Comment by kneekoo** [comment]
That "generic warning" happens too late, which makes it completely useless in this scenario.

The Update Manager should at the very least refuse to try to install the updates when the download size is bigger than the available free space. This leads to uselessly download packages that only fill up the storage, with no means to actually use them to update, and it leaves the user having to do some cleanup that can easily be prevented by a check. A plethora of bad things can happen when there's no free space, depending on what's running and what's it doing.

Regarding DKMS, we can at least check if there are any drivers using DKMS, and if there's barely enough free space for the downloaded packages (<download-size+200MB), the update manager should issue a warning that a clean up is advisable for a successful update.

Additionally, the warnings could be accompanied with a link/button to a web page or local documentation explaining how the updates work, why we need enough available storage space and even suggest a few useful things, like applying only the most important (security) updates to stay secure while taking care of the available free space, or remove whatever software we never or very rarely use, etc.

**Comment by gm10** [comment]
The generic warning is desktop specific and percentage based, I suppose that can make it late on very small partitions at default settings. 

I'm not disagreeing with you on the rest, the question is just how much effort you put into something that's not gonna be a problem for most users. Like take the situation in your screenshot, with a ton of updates selected. In an ideal world we could detect the low disk space situation and switch to a single update mode where updates get downloaded and installed and cache cleared again one after another instead of the current operation which is to download everything first and then install it all in one go. That would minimize disk space usage during updates at the cost of updates potentially taking more time. 

In an ideal world. In the real world comparing the total download size to available space on the partition holding the cache is something I'll probably add, we'll see about the rest.

**Comment by kneekoo** [comment]
Most people don't even know GitHub exist, so they can offer their input here. But bad partitioning happens frequently, especially with people sharing a storage device for multiple operating systems, giving the Linux distro a rather small partition.

And large batches of updates happen with every new Linux Mint install, whenever the ISO is older than 3 months - most cases, actually. So checking at least the download size would be great, so people don't run into space issues when it can be so easily prevented. Other than that, it remains to be seen.

Thanks for your reply! :)

**Comment by gm10** [comment]
> P.S. I think the single update mode would be more work than it's worth. 

My point exactly. ;) There's a lot of things that could be done, but someone has to find the time to do them, and it's not like we're getting paid for this, this is volunteer work. So you gotta pick your battles. But the size thing is on my radar. It's also an issue for meta-packages because we don't currently recurse into them for the total size calc. Eventually...
