### ISSUE TITLE
Prefefences / Einstellungen window hight to low

### ISSUE THREAD

**Issue by ehtron** [linuxmint/mintupdate#370]
LM 19 Cinnamon 64 
Mintupdate 5.4.0

the preferences / Options window is in the german language setup is not high enough...
the second kernel option is not visible whithout scale the window.

regards ehtron

**Comment by xenopeek** [comment]
It looks to be because the first sentence under "Aktualisierungen" (Updates) is much longer than the original English. See screenshot:

![screenshot](https://i.imgur.com/DCQHcm8.png)

**Comment by ehtron** [comment]
No.. 
if scale the window, the second checkbox is visible

**Comment by JosephMcc** [comment]
> No..
if scale the window, the second checkbox is visible

@xenopeek is correct. We don't know how long any given string can be when translated. That leaves two options. 1) Scale the window to fit or 2) Put the content in a scrolled window to if the translations are longer the user can scroll the area to see it all.

We went for 2) because the scaling the window can lead to other issues. Like the window becoming too tall to fit on screen.

**Comment by JosephMcc** [comment]
I'm reopening this because there is an issue. You should be getting a scroll bar in the case being shown but you do not.
