### ISSUE TITLE
mintupdate-cli ignore lack of wildcard support / documentation shortcomings

### ISSUE THREAD

**Issue by ehtron** [linuxmint/mintupdate#372]
Hi :)
mint 19 tara 64 cinnamon

ignore in mintupdate-cli does not work...
like

linux-headers-4.15.0-24-generic
linux-modules-*
linux-image-*
linux-modules-extra-*

in /etc/mintupdate-cli.blacklist or /etc/mintupdate.blacklist and
 -i / --ignore parameter also.

/usr/bin/mintupdate-cli upgrade --ignore linux-headers-4.15.0-24-generic --refresh-cache --dry-run --yes

we need a prameter like the kernel settings in the gui options to ignore kernel updates...

regards ehtron

**Comment by ehtron** [comment]
there ist no way to use the cli without kernel-updates...

**Comment by gm10** [comment]
This is partially user error: mintupdate groups updates by source name, thus the ignore/blacklist feature expects the source name, not the package name. Both in the GUI and in CLI.

I'll however flag this as a bug because
* blacklist handling is inconsistent between GUI and CLI (in particular no wildcard support in CLI),
* documentation should clarify the source name requirement,
* and while not technically a bug, I also agree there probably should be an option to ignore kernel type updates
