### ISSUE TITLE
mintupdate-cli crashes apt system after waiting for user intervention

### ISSUE THREAD

**Issue by ehtron** [linuxmint/mintupdate#376]
Hi :)
Mint 19 cinnamon 64 upgrade ..
mintupdate-cli hangs after wait for user intervention. 
(german-version)
from mintupdate.log
debconf: greife zurück auf die Oberfläche: Readline
Konfiguriere grub-pc

Eine neue Version (/tmp/grub.mCTV78EbhW) der Konfigurationsdatei 
/etc/default/grub ist verfügbar, aber die installierte Version wurde verändert.

  1. install the package maintainer's version
  2. keep the local version currently installed
  3. show the differences between the versions
  4. show a side-by-side difference between the versions
  5. show a 3-way difference between available versions
  6. do a 3-way merge between available versions
  7. start a new shell to examine the situation
Wie wollen Sie mit der geänderten Konfigurationsdatei grub verfahren? 

mintupdate-cli stops...... and wait..........

after reboot, the dpgk system is corrupt.
E: Der dpkg-Prozess wurde unterbrochen; Sie müssen manuell »sudo dpkg --configure -a« ausführen, um das Problem zu beheben.
E: _cache->open() failed, please report.

not good for users who want to use the automatic update
regards ehtron :)

**Comment by Yvan-Masson** [comment]
Hi,

I am not a developer, but I think a possible solution would be:

- to add an option to `mintupdate-cli` script that would be used only when started from `/etc/cron.daily/mintupdate`

- to modify `mintupdate-cli` so that when started with this option, `subprocess.call()` uses `DEBIAN_FRONTEND=noninteractive` environment variable.

Regards,
Yvan

**Comment by Yvan-Masson** [comment]
The code is done, I still need to test it before publishing it.
