### ISSUE TITLE
mintupdate window too large

### ISSUE THREAD

**Issue by ramsay-jones** [linuxmint/mintupdate#378]
The 'Update Manager' window (v5.4.0, Mint 19 Tara, cinnamon) is too large for
my screen (1366x768) with the font sizes I have set (my eyesight is not the best!).
With the exception of the window title, I have boosted the font sizes from 10->12pts.
This means I have to ALT-drag the window upwards to see the 'download size' info
in the status bar, because the window will not allow me to resize it (vertically) with
the mouse (why not?). This is not a very good UI - I should be allowed to resize
the window. (BTW, the font sizes used in the Tool-Tips for the 'applets' in the panel
are not consistent - only mintupdate has a larger font size!).

**Comment by xenopeek** [comment]
With default font size the minimum window height is 656 pixels. With fonts set to 12 pts that increases to just 693 pixels. It should fit on your screen. Does perhaps the "Please set up System Snapshots" (in orange) notification bar at the top of the window display because you've not set that up? Indeed, that notification bar adds to the window height, making it too high to fit on your screen. You can either set up System Snapshots (recommended) or disable this notification in Update Manager's preferences.

**Comment by xenopeek** [comment]
You can also disable the local mirror notification bar in Update Manager's preferences. Like the other other notification bar, it increases the height of the window to be too high for your screen.

**Comment by JosephMcc** [comment]
This should be improved by: https://github.com/linuxmint/mintupdate/commit/950860e8469c84469f1cac82f6ce419a31f51bb5

**Comment by ramsay-jones** [comment]
OK, so I have been playing some more. When I remove the 'local mirror' message, the height of
the window is still such that the bottom panel covers the status bar. If I now set the bottom panel
to auto-hide, I still can't see the status bar, but it will now let me resize the window vertically!
If I resize the window to as small as it will go, I can now reset the bottom panel to 'always show'
and still see the status bar \o/.  So, I think the code to size the window has to take account
of the presence/absence of the 'info messages' (for want of a better name).
(Yes, I have now disabled that message in the preferences). HTH ;-)
