### ISSUE TITLE
Feature request: share a cache with apt-run-from-the-terminal

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/mintupdate#387]
If I do `apt update && apt upgrade` in a terminal, sometimes I'd like to be able to read the changelog of upgradeable packages - to be able to read it in MintUpdate. Yet, after `apt update`, MintUpdate does not show upgradeable packages. It shows them only after, wastefully, I do another package trawl by refreshing MintUpdate.

Apologies if this has been reported before; I could not find an existing update.

Mint 18.3 Cinnamon. Mint Update 5.4.1

**Comment by gm10** [comment]
Just run `mintupdate` again for the same effect (make sure to disable the auto-refresh after startup in Update Manager - set timers to 0).

Although I don't understand why you'd want to update on the command line to then read changelogs in Update Manager. Pick one or the other. 

Just for completeness sake: Update Manager could theoretically monitor /var/cache/apt/pkgcache.bin for modifications and grab a new list of updates when a change is detected, but then the same same argument could be made for any change in apt configuration files, in particular pins, so I don't think I really support this (not that it's my decision), seems a bit much for an "issue" that the normal user using only Update Manager never runs into.

**Comment by CottonEaster** [comment]
Thanks for the reply.

> Just run mintupdate again for the same effect (make sure to disable the auto-refresh after startup in Update Manager - set timers to 0).

So I have to close the application if it is running already and ensure it is not entrayed and then run it again? That seems somewhat involved.

> Although I don't understand why you'd want to update on the command line to then read changelogs in Update Manager. Pick one or the other.

Because I am unfamiliar with doing it on the command line. But perhaps you have a point.

As to the rest of what you say: I think I see your point, but you can appreciate, I hope, that it irritates to have updated the cache and for the Update Manager to be oblivious of it. Still, I will close this issue.

**Comment by gm10** [comment]
> So I have to close the application if it is running already and ensure it is not entrayed and then run it again? 

You don't actually, mintupdate kills all running instances itself when you start it. 

> Because I am unfamiliar with doing it on the command line. But perhaps you have a point.

There's the `apt changelog <packagename>` command, which is however rather limited at the moment (only works for packages from the Ubuntu repos). I actually wrote a replacement for that the other day which handles all sorts of packages - I'll probably stick that into a pull request soon (I have an extensive one open for Mint's apt wrapper, anway) and if they accept it then it may make it to a Mint near you eventually. But I digress:

> As to the rest of what you say: I think I see your point, but you can appreciate, I hope, that it irritates to have updated the cache and for the Update Manager to be oblivious of it. Still, I will close this issue.

No, of course I understand where you are coming from. I think it was a valid suggestion, and the Mint team might take a different view than I on whether this is worth looking into. So don't close it just because of my comment (should that have been the case).
