### ISSUE TITLE
Kernel new update module doesn't display installed low-latency kernel

### ISSUE THREAD

**Issue by morton-f** [linuxmint/mintupdate#432]
Why this is a problem: User can't know beforehand about this peculiarity and after installing several generic and low-latency kernels is presented with misleading information which leads them to wrong conclusions. 
I think that information about low-latency kernel upgrades is of little importance but information about installed ones and possibility to remove them would be highly appreciated. 
```
$ inxi -S
System:    Host: vLM191 Kernel: 4.18.20-041820-lowlatency x86_64 bits: 64 Desktop: Cinnamon 4.0.5
Distro: Linux Mint 19.1 Tessa 
$ mintupdate --version
5.4.4
```
How to reproduce: Install any low-latency kernel from synaptic or from Ubuntu mainline kernels with CLI:
```
wget -c http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.16.18/linux-headers-4.16.18-041618_4.16.18-041618.201806252030_all.deb
wget -c http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.16.18/linux-headers-4.16.18-041618-generic_4.16.18-041618.201806252030_amd64.deb
wget -c http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.16.18/linux-image-unsigned-4.16.18-041618-generic_4.16.18-041618.201806252030_amd64.deb
wget -c http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.16.18/linux-modules-4.16.18-041618-generic_4.16.18-041618.201806252030_amd64.deb
sudo dpkg -i *.deb
```
http://i.imgur.com/Y0yCAQG.png

**Comment by gm10** [comment]
Update Manager only supports either -generic or -lowlatency, but not both at the same time. That's not new, it has always been this way (actually I fixed something even about the -lowlatency support this release that didn't work correctly before). I'm not sure why the decision to separate them was made, probably to avoid confusing users into installing the wrong variant.

You can switch the whole of Update Manager over to use lowlatency kernels by running this:
`dconf write /com/linuxmint/updates/use-lowlatency-kernels 'true'`
To toggle it back:
`dconf write /com/linuxmint/updates/use-lowlatency-kernels 'false'`

You will need to re-open the kernel window to see the effects. If you refresh or restart Update Manager it will also offer you Ubuntu's regular -lowlatency kernel, so don't get confused there, there is no indication as to what variant it is other than in the small print at the bottom of the description tab. The kernel window shows no indication at all.

Furthermore, while automatic updates, if enabled, will keep updating an installed -lowlatency meta package, they will additionally install the -generic variant unless you change the root user's dconf setting as well with the above command.

I do agree that it should always show the installed kernels of the other variant, even if both variants don't get fully integrated (although they probably should, based on a configuration option with a big warning next to it). 

Please do leave this issue open. Since it may be more pertinent with mainline users, maybe even raise it as a beta issue https://github.com/linuxmint/mint-19.1-beta/issues to get it on the road map for 19.2, if Clem so desires (if you do post there please include a link back to here though). Maybe even ask for an option to enable installation of mainline kernels while you're at it. The two topics are somewhat linked - how far do we want to protect new users from potentially harmful options.

**Comment by morton-f** [comment]
> You can switch the whole of Update Manager over to use lowlatency kernels by running this:
> dconf write /com/linuxmint/updates/use-lowlatency-kernels 'true'

-Thank you very much for the information about this _dconf_ parameter, it allows to stay in the comfort of the Update Manager. Maybe you consider the possibility to implement a GUI switch between standard and the 'advanced' 'lowlatency' mode (with relevant window title or another way).

> Furthermore, while automatic updates, if enabled, will keep updating an installed -lowlatency meta package, they will additionally install the -generic variant

-I noticed something like  that, one can install generic Ubuntu kernel from standard mode alongside already installed lowlatency kernel, but not otherwise.
