### ISSUE TITLE
"Remove old kernels..." UI suggestions

### ISSUE THREAD

**Issue by s44i7h-sam** [linuxmint/mintupdate#448]
The new "Remove old kernels..." feature (Mint Update) addresses the real need for removing multiple kernels at once, yet the UI approach is confusing. The popup disorients the user by reversing the list order as well as removing the uninstalled kernels from the list, and the user now has to look for reference and orientation in the greyed out list in the main window which is now unresponsive to scrolling. The approach makes sense only if you want to remove ALL "old" kernels and don't need to look at the list at all [see bellow for another issue with "old"], but not if you want to remove selectively (and in the former use case just a simple button in the main window would do). The old approach, although tedious, did at least not disorient by hiding and moving kernels around in the list.

I would suggest that instead of introducing a new window with yet another selection and sorting of the same kernel list you simply integrate the removal checkboxes into the existing list in the main kernel window. Just show the removal checkbox next to installed-and-unactive kernels, then at the bottom you could, for example, put two buttons: "select all kernels" and "remove all selected kernels". And if you want the user to be able to show just the installed kernels then you could also add a toggle button at the bottom with a changing label: "show installed kernels" <-> "show all kernels".

Of course the main window UI would not be as "minimalist" but better a few additional UI elements than separating and repeating the same thing (Linux kernel list) in two different ways and in two separate windows.

---

Not all kernels shown by the removal window are in fact old, despite the button label and window title "Remove old kernels...". Just now there was an update for a new 4.15 kernel (4.15.0-20) which is as of now labeled as "unsupported" in the main window (but that is a separate issue). The "Remove old kernels..." feature includes it in the removal list.

If any installed-and-unactive kernel is selected by default in the removal list, this only confuses the user (along with the already mentioned list order reversal). Here's a simple and frequent use case: new kernel comes out and the user installs it via mint update. Then the user opens the mint update's kernel list to remove any old kernels left. The user presses the "Remove old kernels..." button and then "Remove selected kernels". What just happened is that the user has removed the newly installed kernel because it is not yet active.

The problem is twofold: misleading label ("Remove old kernels...") and default selection including newest (or newer-than-active) version(s) as well. However, simply not showing the newest version is not a good solution because there can be valid reasons for removing it (e.g. regressions). If the UI remains as it is, at least change the misleading label and deselect by default the newest (or newer-than-active) kernel(s).

**Comment by gm10** [comment]
Thanks for the feedback!

- I'll probably switch the sorting, I have been thinking the same.

- I disagree that having the user sort through the entire list of available kernels to find the installed ones and check boxes to mark them for removal would in any way be easier than the new button aggregating them for you. I won't be changing that.

- Regarding just updated kernels, I did think it would be nice if we marked the current meta-kernel in some way if it's not the active kernel, but I consider it very low priority. If you remove it then you'll just be offered the update again. The regular using receiving kernel updates via the normal update procedure has no need to go to the kernel window at all. To this end I also submitted a change that would allow Update Manager to automatically remove old kernels without user intervention, but unfortunately that feature did not get included in the 19.1 release. 

- Regarding the button label and default selection, kinda same story. For most users the use case will indeed be the removal of old kernels, and they'll want them gone. But instead of just doing it that window  pops up to get you to review the selection. I think it's ok.

**Comment by mjsulik** [comment]
Recognizing that this is a low priority issue, I second that "remove old kernels" confusingly automatically selects newer, inactive kernels for removal. Perhaps a solution would be to compare version numbers and only automatically select older kernels for removal?

**Comment by gm10** [comment]
@mjsulik that's a good idea, I'll do that, thanks.

**Comment by gm10** [comment]
Actually on second thought it's not that simple, an LTS kernel with a lower version number might be newer than an end of life HWE kernel. Might have to check support status, too. I'll think about it.

**Comment by mjsulik** [comment]
Could you only remove older kernels within each minor version? For example, for someone who has 4.15 and 4.18 installed, you would never delete the most recent version for each of these?
