### ISSUE TITLE
Restart button after update.

### ISSUE THREAD

**Issue by alan7000** [linuxmint/mintupdate#451]
Hello, I come to propose a little idea which consists in proposing to the user to restart his computer after an update which requires it. Example: kernel update.

**Comment by ewangi** [comment]
I agree with this idea. Can I also propose that the list of kernel versions obtained through View->Linux kernels uses "Installed (reboot to make active)", or similar, instead of "Installed" for a kernel version if it has been installed since the last reboot and is due to be made active at the next reboot.

**Comment by gm10** [comment]
It's sort of on the roadmap already (seems to have ended in the wrong category "non blocking bugs").

I'm not sure about a good implementation though. Kernel and firmware updates are a given I suppose, but what about system services or running apps. Should we then scan the contents of every package that was updated to determine what was in it, scan all running processes and services for matches and display a warning then? 

This might be overkill, but not doing it might have the user falsely rely on the notification. Besides, while a reboot will help with everything, simply restarting active services and processes would do the job as well and some packages actually include that in their post installation scripts. So maybe just a general label somewhere that some updates may require a reboot? I really don't know.

This one however I'm fairly certain is not going to happen:
> Can I also propose that the list of kernel versions obtained through View->Linux kernels uses "Installed (reboot to make active)", or similar, instead of "Installed" for a kernel version if it has been installed since the last reboot and is due to be made active at the next reboot.
To determine what kernel the system would boot up with automatically would require scanning the boot configuration, which is very much non-trivial even if we supported only GRUB2. My system is configured such that newly installed kernels do not become active automatically after a reboot, for example. And the user can choose to boot with any installed kernel at the boot menu, anyway.

**Comment by ewangi** [comment]
Perhaps some sort of a combined approach would be possible, where those areas where a reboot is known to be required (kernel, firmware, etc.) are flagged with a "Reboot required" message, whereas the general label would cover everything else.

I suppose the first thing to ask for questions like these is "What would the ideal situation be, if resources were not an issue"? Then after that: "So is this feasible given resource constraints (and, if so, what are the costs and the benefits)?"

For me, the ideal situation would be where mintupdate could indeed work out whether or not a reboot was required after the update, or installation, of a package and would issue the advisory accordingly. But, as you point out, is this actually feasible? It almost sounds as if it is something that should have been designed into the package system in the first place, where the package itself flags at the end of its installation/update whether or not a reboot is required. It would thus have been the responsibility of the package itself to determine this piece of information that can be difficult to determine otherwise. But, sadly, this is not the case.

Oh well, I gave it a go with my "Installed (reboot to make active)" suggestion. ;)

Out of interest, how is your system configured so that it doesn't auto activate newly installed kernels?

**Comment by gm10** [comment]
Notes to self:

I have been looking at `checkrestart` and `needrestart` (https://github.com/liske/needrestart). The first one doesn't work correctly at all on my system, the second one is much better (so far false positives only when re-installing the same version). 

The second one is at the same time great for allowing interactive restarting of services relying on updated libraries, and dangerous for that same reason (it'll offer to restart lightdm no questions asked, which would kill all graphical user sessions). 

Theoretically the output from the non-interactive version could be used in mintupdate to simply recommend a restart in all cases (even though only kernels strictly need it), but execution time of the tool is several seconds (over 6 seconds on my laptop), I'm not sure that would be acceptable. --> maybe warn automatically only after kernel updates and add a toolbar button to allow a manual check for processes and services in need of restarting?
