### ISSUE TITLE
Update Manager not showing latest mainline kernels?

### ISSUE THREAD

**Issue by ewangi** [linuxmint/mintupdate#452]
Perhaps I am misunderstanding this, but the Mint 19.1 release notes state that "The Update Manager is able to list mainline kernels and to show their support status".

By this, I assumed that the kernels at https://kernel.ubuntu.com/~kernel-ppa/mainline/ would be listed, at least the ones which are still supported either by Ubuntu or by kernel.org.

The latest kernel that the Update Manager is currently offering is 4.18.0-13. However, the latest available kernel range supplied by Ubuntu at the above site is 4.20 (just released) while 4.19 is also available.

Mint 19.1 MATE. Update Manager 5.4.7.

**Comment by gm10** [comment]
It seems that @clefebvre likes to cause misunderstandings about that feature, that's why he never clearly says what it does in his blog posts. :)

Update Manager will only list **installed** mainline kernels and allow you to remove them. 

Also all mainline kernels are **unsupported**. They are compiled by Ubuntu for testing purposes, but you are using them very much at your own risk (e.g. for the longest time 4.19 and pre-release versions of 4.20 would corrupt your disk, 4.19 still has a fat memory leak in one of the wifi drivers, _et cetera_).

It is for this reason that installation of mainline kernels is **not a public feature**, because no matter how many warnings I stick on it, users will still do it and potentially lose their data (going by forum reactions, 4.19 caused a lot of such "fun"):
![mintupdate-mainline](https://user-images.githubusercontent.com/13855078/50538901-d095c200-0b77-11e9-9c92-21488c1f5d60.png)

**Comment by ewangi** [comment]
Thank you for your explanation, gm10. Don't worry, I don't plan to install any unsupported kernels in order to share some of the fun. :) I was just wondering why something I thought was the case didn't appear to be so in reality. I assumed that Mint was now providing a way for folk to avoid having to resort to ukuu or other methods to install mainline kernels, but obviously not (and probably a good idea too from what you say). Cheers.

**Comment by gm10** [comment]
No worries, it's only natural you would have understood the blog post that way, I'm sure I would have read it the same way if I was an innocent bystander. 

Maybe we'll release the feature eventually. There's another open issue about how we currently support -lowlatency kernel builds. To me both issues are linked insofar as they both touch upon options useful for experienced users but potentially harmful for the inexperienced. Comes down to a policy decision I guess, which isn't down to me.
