### ISSUE TITLE
Bug? Update Manager can't see all available Linux Kernels. Plus Suggestion. 

### ISSUE THREAD

**Issue by setsunati** [linuxmint/mintupdate#469]
Update Manager only see's up to 4.18 Linux Kernel version. :(

Ubuntu currently shows Linux Kernel v5.0 RC5 but i can only see 4.18 in Update Manager.
https://kernel.ubuntu.com/~kernel-ppa/mainline/?C=N;O=D

I want to install Linux Kernel 4.19 or above using Update Manager. 
I can't use Ukuu since it became a paid software.

If its a bug, hope you fix it soon. 

If Update Manager is not showing all available Linux Kernels on purpose, 
I have a suggestion: 
An option i can enable in Update Manager > Preferences. 
So i and other users who want to install latest kernels can see all available Linux Kernels from Ubuntu and easily install it. 
This way i wont have to use terminal and wont have to manually download .debs to install Linux kernels on Linux Mint.

Visual representation: https://i.imgur.com/P9IKcI4.png
Option can by kept turned off by default so users who want to install latest kernels can enable it to see all available kernels from Ubuntu and install kernels at their own risk.

**Comment by gm10** [comment]
No bug, the kernels you linked are intentionally not included. They exist only for testing purposes and are described by Ubuntu as: 

> These kernels are not supported and are not appropriate for production use.

**Comment by setsunati** [comment]
That's why i am suggesting an option i can enable from preferences so i can install latest kernels easily at my own risk. @clefebvre @gm10

**Comment by gm10** [comment]
That's for @clefebvre to decide but my understanding is that's currently not desired.

**Comment by setsunati** [comment]
Which file should i edit in mintUpdate so i can configure Update Manager myself so it can show me all available kernels? If it is possible to do it.

**Comment by gm10** [comment]
That's no simple edit unfortunately. This needs a code change which isn't included in the release version of Update Manager. 

Because those aren't official kernels, just test builds, there is no official distribution channel for those, i.e. despite the name "PPA" in them there is no actual PPA you can just add.

**Comment by gm10** [comment]
That's not a simple edit, this needs a code change which we don't include in the release version of Update Manager. 

Since these are unverified test builds there is no official distribution channel for those, so despite the name PPA in the URL it's no actual PPA you can add. 

If you can however add this PPA: https://launchpad.net/~canonical-kernel-team/+archive/ubuntu/unstable?field.series_filter=disco, which is Ubuntu's unstable kernel build PPA. There's a 5.0 series build for upcoming Ubuntu 19.04 in there. Use at your own risk.
