### ISSUE TITLE
"Automated Maintenence" removed my wallpaper (mint-backgrounds-tessa)

### ISSUE THREAD

**Issue by momo42** [linuxmint/mintupdate#570]
I freshly installed my PC when Mint 19 came out. After the upgrade to Mint 19.1 I switched my wallpaper to one of the new tessa wallpapers. When 19.2 came out I upgraded to it and left my wallpaper as it was.

Nothing happend till I activated "Remove obsolete kernels and dependencies" under Preferences>Automation. Some days later my pc welcomed me with the well-known default wallpaper. It took me a while to realize that mint-backgrounds-tessa had been removed.

it's a bit annoying that packages that are actually in use are removed due to missing dependencies. I have no idea how to check what other packages got removed after activating this option. In fact I checked this option only to have obsolete kernels removed automatically.

The package mint-backgrounds-tessa got removed from four different pcs after activating this option.

I think that the real problem is not mintupdate itself but the fact, that mint-backgrounds packages are not 'protected against removal' after upgrade to the next mint version. This new option in mintupdate just triggers the problem by stealing the users' wallpapers. :-)

Please get this fixed in one or another way.

OS: Mint 19.2
mintupdate 5.5.4

**Comment by kelebek333** [comment]
This is a normal case. Because the mint-backgrounds-tessa package was the dependency of the mint-artwork package. Depency of mint-artwork package changed with mint-backgrounds-tina on Linux Mint 19.2. Therefore, mint-backgrounds-tessa was non-dependent package. For this reason, Update Manager's automation tool has been deleted the package.

**Comment by kelebek333** [comment]
This is a normal case. Because the mint-backgrounds-tessa package was the dependency of the mint-artwork package. Depency of mint-artwork package changed with mint-backgrounds-tina instead of mint-backgrounds-tessa on Linux Mint 19.2. Therefore, mint-backgrounds-tessa was non-dependent package. For this reason, Update Manager's automation tool has been deleted the package.

If you wish to use that backgorunds, you can manually install mint-backgrounds-tessa package. It will not be installed as dependent on another package, so it will not be deleted by the automation tool.

`sudo apt install mint-backgrounds-tessa`

**Comment by momo42** [comment]
Thanks for your explanation. I've already done what you suggested.

The thing is, that this issue (wallpapers that are in use magically disappearing) might hurt **every** Mint user that enables this checkbox. It took me a while to understand what went wrong because there was no direct temporal connection between activating the option and losing my wallpaper. And I needed more time to figure out what package my wallpaper was in.

I hope you agree that confusing users by silently deleting their wallpapers is not a wanted side effect. Might not be the right place to complain because `sudo apt autoremove` would have done the same - but not silently! This HAS to be fixed somewhere.

And that leads me to the other (more important) question.
How can I see what other packages got removed by activating this option?

`mint-backgrounds-tessa` was definitely needed but not protected by dependencies. I have no idea what other wanted packages got lost. :-/

**Comment by gm10** [comment]
> This HAS to be fixed somewhere.
How should the software know you want to keep a package from a previous point release that users doing a clean install wouldn't even have? 

> How can I see what other packages got removed by activating this option?

`zcat /var/log/mintupdate.log*`
