### ISSUE TITLE
mintupdate doesn't start: ImportError: pycurl

### ISSUE THREAD

**Issue by 1Maxnet1** [linuxmint/mintupdate#573]
**Describe the bug**
When I want to start the application, nothing happens. When I want to start mintupdate from within the commandline, an error occurs:

**To Reproduce**
1. Go into the Terminal
2. Enter "mintupdate"

**Expected behavior**
Mintupdate should start

**Distribution:**
- [X] Linux Mint 19.2

**Logs:**
Copy & paste the log output from Update Manager > View > Information here.

**Crash report:**
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintUpdate/mintUpdate.py", line 17, in <module>
    import pycurl
ImportError: pycurl: libcurl link-time version (7.58.0) is older than compile-time version (7.65.2)

**Comment by AtomicRobotMan0101** [comment]
it seems this might be back.

For some reason it broke - Im not running a python dev env on this machine either.... its a standard safe boring box for browsing.

Correcting it has proven impossible.  The Python ecosystem’s mix of system vs user vs venv vs pipx vs apt is deeply fragmented - it has made the life of ordinary users a goddam nightmare.

e.g., when attempting to fix this via

` > pip install --no-binary :all: pycurl`

>
>    error: externally-managed-environment
> 
>    This environment is externally managed
>    To install Python packages system-wide, try apt install
>     python3-xyz, where xyz is the package you are trying to
>     install.
>     
>     If you wish to install a non-Debian-packaged Python package,
>     create a virtual environment using python3 -m venv path/to/venv.
>     Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
>     sure you have python3-full installed.
>     
>     If you wish to install a non-Debian packaged Python application,
>     it may be easiest to use pipx install xyz, which will manage a
>     virtual environment for you. Make sure you have pipx installed.
>     
>     See /usr/share/doc/python3.12/README.venv for more information.

Great. Locked out.

Let get a bit more aggressive.....

` sudo apt-get install build-essential libcurl4-openssl-dev python3-dev`
` pip uninstall pycurl`
` pip install --no-binary :all: pycurl`

Same result. Humph.

More aggressive....

` sudo apt install python3-full python3-venv libcurl4-openssl-dev`
` python3 -m venv ~/pycurlfix`
` source ~/pycurlfix/bin/activate`
` pip install --upgrade pip setuptools wheel`
` pip install --no-binary :all: pycurl`

Same result with the error above about it being externally managed.

At this stage I feel Im about to cause a catastropic mistake and lobotomise the system.... so Ill just report it and do the updates manually.

**The problem is the python pycurl.....**
