### ISSUE TITLE
Update system is trying to be more like Windows

### ISSUE THREAD

**Issue by Elzoog** [linuxmint/mintupdate#587]
When updating the kernel, please provide basic information about why I should reboot.  If the kernel only provides a minor bug fix then I should be able to simply ignore it. If there is a major bug or system fix, please provide that information as well.

I don't want Linux to become like Windows where the system just automatically updates whenever it wants and interrupts whatever it is I am doing.  I should not be seeing messages such as "please reboot your system as soon as possible" unless I know what is being corrected and how it could affect me if I continue using the computer without rebooting.

**Comment by clefebvre** [comment]
Well, you're not using the new kernel until you reboot.. so if you just installed a new one, that's what the message is for.

In terms of changes, there's a changelog available.

As for being more like Windows, I don't know what that means... you want us to shove updates down your throat and prevent you to log in while they're being applied? Seriously, do we need to mention Windows here?

**Comment by Elzoog** [comment]
"Well, you're not using the new kernel until you reboot.. so if you just installed a new one, that's what the message is for."

I understand that.  I have been using Linux since the 1990s when Red Hat 4.0 came out.  It's just that I don't remember ever being nagged with a message saying, "please reboot your system as soon as possible" until recently.  I don't want to see a message like that unless the update is REALLY important.

**Comment by clefebvre** [comment]
Kernel updates come very often and they're filled with changes. Nobody at Mint, or Ubuntu, or probably even upstream from that is trying to assess how important it could be to you, in your particular situation, to reboot or not. The thing is, anything that includes a security fix, or which is served through a security channels (and that's the case for kernels), is deemed REALLY important.

The thing is, unless you actually read the changelog, and go through the git changes upstream in the kernel repository, you won't really know what's at stake. And since nobody does that, what do we tell people by default? You can't expect the update manager to have a clue about this.. and if it did it would rely on metadata which doesn't exist upstream yet.

The message is "You have installed updates that require a reboot to take effect, please reboot your system as soon as possible.". It sits on the fence and hits at urgency because we're dealing with not only updates here but also security fixes. It's not able to know whether that reboot is urgent or not.
