### ISSUE TITLE
Wrong description displayed for grouped updates

### ISSUE THREAD

**Issue by kneekoo** [linuxmint/mintupdate#609]
**Describe the bug**
The update displays the description of a dependency.

**Screenshots**
![bug-wrong-description](https://user-images.githubusercontent.com/566306/77348456-c7bf7c00-6d39-11ea-84cd-b5b24c48c677.png)

![bug-wrong-description-2](https://user-images.githubusercontent.com/566306/77378586-a4ff8880-6d76-11ea-8d15-cd92ffddfb30.png)

**Distribution:**
- [x] Linux Mint

**Software version:**
5.5.9

**Comment by kneekoo** [comment]
In this case, it's not even the last package's description, but another's.

![bug-wrong-description-3](https://user-images.githubusercontent.com/566306/77660052-21fa5000-6f79-11ea-8ded-952f0a19be57.png)

**Comment by kneekoo** [comment]
This is still an issue with mintupdate 5.7.3 in Mint 20.1, with the LibreOffice Fresh PPA*

* ppa:libreoffice/ppa

**Comment by felipecespedes** [comment]
@kneekoo the issue is still there. 
The fix I applied was reverted in https://github.com/linuxmint/mintupdate/commit/44d28141a051af2f85874dfc0003426ded6aa856, I left a comment on that commit explaining the issue to the maintainer but there was not any response.

Since this issue is closed, then should we open a new one?

**Comment by kneekoo** [comment]
I think we can wait for a bit, considering @mtwebster will be notified of activity here. This should be reopened rather than creating a new issue.

**Comment by kneekoo** [comment]
@mtwebster @clefebvre Should I open a new issue or can this one be reopened?
