### ISSUE TITLE
update issue

### ISSUE THREAD

**Issue by KJ4SLE** [linuxmint/mintupdate#632]
E: dpkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem. 
E: _cache->open() failed, please rep
![Screenshot from 2020-07-07 12-01-28](https://user-images.githubusercontent.com/67969490/86809409-d95b3400-c049-11ea-9c44-d27a4c6e1df1.png)

**Distribution:**
- [x ] Linux Mint
- [ ] LMDE
- [ ] Other (please specify)

**Software version:**
See Help > About in Update Manager.  5.5.9

**Logs:**
Copy & paste the log output from Update Manager > View > Information here.

**Crash report:**
If you are reporting a crash, please run `mintupdate` from a terminal window, reproduce the crash and copy & paste any output from the terminal window here.

**Additional context**
Add any other context about the problem you think might be relevant.

**Locale:**
If the problem is with text not getting displayed correctly, paste the output of the terminal command `locale`.

**Comment by xenopeek** [comment]
This is an observation not a bug. That the dpkg error is shown by mintupdate doesn't mean it's caused by mintupdate. To find the cause would need further troubleshooting. See out [troubleshooting guide](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/) for more info. Such error can happen when some package install or update was interrupted, or configuration or EULA acceptance was aborted.

Run the command in terminal to hopefully solve the issue. You need to be root for system administration tasks so run it as `sudo dpkg --configure -a`.
