### ISSUE TITLE
setting 'remove old kernels' has no effect

### ISSUE THREAD

**Issue by oz42** [linuxmint/mintupdate#648]
In contrast to Mint <=19.3, the setting 'remove old kernels' is ignored in 20.0. I have >2 kernels installed here.
Reproducable: on 2 machines.

**Distribution:**
- [X] Linux Mint 20.0

**Software version:**
5.6.9

**Comment by xenopeek** [comment]
Do you mean the "Remove obsolete kernels and dependencies" switch in Preferences > Automation? Mind the note on that:

> This option always leaves at least one older kernel installed and never removes manually installed kernels.

Can it be the case you have manually installed (not as a regular update through Update Manager) those older kernels you think should have been removed?

Mind also that automatic removal runs once a week and, I think, it will start between 3 and 4 hours after logging in to Linux Mint. Might it be the case you have enabled this option shorter than a week ago or that you keep your computer on for shorter amounts of time than 3-4 hours?

Otherwise please run these two commands to check status of the automatic removal timer and service and share the output here (you can select and copy text from the terminal through the Edit menu, after pasting it here select the pasted text here and click the < > insert code button on top of the text input field to mark the pasted text as code so it will used fixed-width font for readability):
```
systemctl status mintupdate-automation-autoremove.timer
systemctl status mintupdate-automation-autoremove.service
```
Also check your `/var/log/mintupdate.log` log file and see what if anything you can find about automatic removal or any errors related to that.

Finally please also simulate what automatic removal service does by running this command (it only simulates the command, it doesn't actually perform it):
```
sudo apt-get --simulate autoremove --purge -y
```
Share the output of that command as if it does say it will remove kernels.

**Comment by clefebvre** [comment]
This is mitigated by kernel postinsts themselves: /etc/apt/apt.conf.d/01autoremove-kernels specifically preserves some of the older kernels.
