### ISSUE TITLE
Automatically fix package problems

### ISSUE THREAD

**Issue by MidnightNerd** [linuxmint/mintupdate#669]
It sometimes happens that the package system generates errors. In some cases of Errors automatic Upgrades aren't applied anymore. 
As unexperienced Users don't look in the Update Manger this can result in real security issues.

**Describe the solution you'd like**
Inform users when there is a problem with upgrading packages that can't be fixed automatically,
If user interaction is required--> ask user to manually go to the configuration process or to use mintupdate-cli -y upgrade.
As far as it's possible: automatically fix the problems (e.g. sudo dpkg --configure -a)
Inform users when LinuxMint reaches EOL-->regularly ask for starting the upgrade process when there is a recent timeshift backup.

**Additional context**
I know the error fixing errors in dpkg automatically can be hard.
However the most important thing is that the user gets informed, when the system does no updates(len(stderr)==0 of mintupdate-cli could be a good indicator, but it may also be not 0 when network isn't connected)
 or LinuxMint reaches EOL,
so they can ask a more experienced user to fix the issue.

I hope i'm not wasting your time with this issue. But i really think this could be usefull for Linux-Newbies.

**Comment by Lurux** [comment]
The EOL is checked by the system reports tool nowadays as far as I know, but I'm unsure if the update manager can warn the user when automatic updates fail to run. Have you been able to verify that ?

**Comment by hirntot** [comment]
any updates on that issue?

**Comment by MidnightNerd** [comment]
Closing this issue for now. As mintupdate has become very stable and errors only occur very rarely. I'm not sure but i think there are now also EOL-indicators and indicators if updates aren't applied.

**Comment by hirntot** [comment]
Hi @MidnightNerd, sorry but I didn't feel your answer at all. I just agreed to the others that I also experienced this issue every now and then. And I still think that it's a serious issue for people supporting noobs with linux. and you close it because it's not an issue anymore? This doesn't feel right for me... 

> errors only occur very rarely.

The word "rarely" is open to interpretation. I assume, this problem occurs once or twice a year, what is your guess? In my perspective, twice a year is one and a half times too often, if I have LinuxMint running on about 10machines in my family, in different cities even.

Are you still sure that this is no issue anymore, even if people report issues with it?
