### ISSUE TITLE
simple typo on update pop-up

### ISSUE THREAD

**Issue by cypre** [linuxmint/mintupdate#695]
Using Update Manager [Mint 20.2 MATE] click the tick "Install Updates' [as per usual procedure] the occasional pop-up, pops up.
It reads:
"This upgdate will trigger additional changes"
which is usual BUT the spelling of upgdate should be update.

![upgdate typo](https://user-images.githubusercontent.com/88773899/129012842-9afecf99-ff63-44ed-a71f-51f2788f90ee.png)

have not yet seen it happen again because have not had similar pop-up notification for additional changes during any updates (yet).

**Distribution:**
- [ ] Linux Mint 20.2 MATE

**Software version:**
mintUpdate 5.7.8

**Locale:**
fruit@fruit-O:~$ locale
LANG=en_AU.UTF-8
LANGUAGE=en_AU:en
LC_CTYPE="en_AU.UTF-8"
LC_NUMERIC="en_AU.UTF-8"
LC_TIME="en_AU.UTF-8"
LC_COLLATE="en_AU.UTF-8"
LC_MONETARY="en_AU.UTF-8"
LC_MESSAGES="en_AU.UTF-8"
LC_PAPER="en_AU.UTF-8"
LC_NAME="en_AU.UTF-8"
LC_ADDRESS="en_AU.UTF-8"
LC_TELEPHONE="en_AU.UTF-8"
LC_MEASUREMENT="en_AU.UTF-8"
LC_IDENTIFICATION="en_AU.UTF-8"
LC_ALL=
fruit@fruit-O:~$

**Comment by xenopeek** [comment]
This is a problem in the English (Australian) translation, here: https://translations.launchpad.net/linuxmint/latest/+pots/mintupdate/en_AU/116/+translate. The translation can be corrected there.

**Comment by cypre** [comment]
thank you  @xenopeek

have gone to the link, needed to register with UbuntuOne in order to register with Launchpad... lots of items to read and agree on, along the way BUT...

It is a bit confusing as the translation jumps from 'upgrade' to 'update' if i was to correct the spelling from 'upgdate' to 'update' ...
so i am presently left guessing as to if it should be upgrade or update??

Looked in my files : 
Located in usr/lib/linuxmint/mintUpdate/mintUpdate.py:460 

only to find much the same BUT with no indication of translation, etc:
------------------------------------------------
Gtk.MessageType.WARNING, Gtk.ButtonsType.OK_CANCEL, None)
                                dialog.set_title("")
                                dialog.set_markup("<b>" + _("This upgrade will trigger additional changes") + "</b>")
                                #dialog.format_secondary_markup("<i>" + _("All available upgrades for this package will be ignored.") + "</i>")
                                dialog.set_icon_name("mintupdate")
                                dialog.set_default_size(320, 400)
                                dialog.set_resizable(True)
------------------------------------------------------------
Not sure if you follow my confusion here? [I am pre-novice, so please forgive my ignorance] but we have an update, the 'original' reads "upgrade" but the warning (see my first post here) would indicate it should read "update".

So i suppose, the question is... should it be translated to 'upgrade' or 'update'?

I will poke around the launchpad translations page that you sent me to, now i am there, and see if i can ring a bell for a little help from the crew there but thought i should politely give you some feedback as you were so kind and prompt to reply.

thank you

**Comment by xenopeek** [comment]
There are words that are spelled differently between English variants (e.g., color vs. colour) but translating "upgrade" to "update" would change the meaning. Take a look at the same translation for English (Canada) https://translations.launchpad.net/linuxmint/latest/+pots/mintupdate/en_CA/116/+translate and English (United Kingdom) https://translations.launchpad.net/linuxmint/latest/+pots/mintupdate/en_GB/116/+translate. They leave it as "This upgrade will trigger additional changes" and I think the English (Australia) translation should use that as well.

We have a translation guide that may help understand a little better how translation works: https://linuxmint-translation-guide.readthedocs.io/en/latest/.

That you couldn't find any translations in your /usr/lib/linuxmint/mintUpdate/mintUpdate.py file is correct. It uses a library called gettext for translations. The translations are stored in separate files. The underscore at the start of  `_("This upgrade will trigger additional changes")` calls gettext to get the translation for your locale. The English (Australian) translations for Update Manager are stored in the file /usr/share/locale/en_AU/LC_MESSAGES/mintupdate.mo on your system. That's a compiled file but command `strings /usr/share/locale/en_AU/LC_MESSAGES/mintupdate.mo  | grep upgdate` confirms the strange "This upgdate will trigger additional changes" translation is in there.

That you find mention of Cinnamon in /mintUpdate.py has to do with that Update Manager can also upgrade [Cinnamon Spices](https://cinnamon-spices.linuxmint.com/) that users have installed — applets, desklets, extensions and themes for Cinnamon. There isn't something like that for MATE. And if you don't have any of those Cinnamon Spices installed — because you're using MATE — that code doesn't do anything. But that's why you find mention of Cinnamon. This was covered in the "What's New" for Linux Mint 20.2 Cinnamon: https://www.linuxmint.com/rel_uma_cinnamon_whatsnew.php. Similarly Update Manager can upgrade flatpak packages but that doesn't do anything if you don't have such installed.

**Comment by cypre** [comment]
Xenopeek @xenopeek  you are a champion!

If i was a bit faster off the block i might have thought of checking the other translations as you suggested.

I shall see if i can go and make some changes without breaking anything.

Thank you for the info and your reply,
much appreciated

For a while there i was thinking that maybe this "upgdate" is some new term i had simply never heard of and since i know next to nothing about all this, it could be possible.

**Comment by cypre** [comment]
i have been and done. 
Please check here for me:
[https://translations.launchpad.net/linuxmint/latest/+pots/mintupdate/en_AU/116/+translate](
https://translations.launchpad.net/linuxmint/latest/+pots/mintupdate/en_AU/116/+translate) 

I notice now that the English AU reads "update" BUT another similar 'upgdate' In Ubuntu is listed now.

**Comment by xenopeek** [comment]
I think that's just Launchad, it suggests translations if it has seen the text in another project and has a translation for it there in your language.

Thanks for the correction. At the latest it will be included with Linux Mint 20.3 later this year. A few times per year, usually before the beta release of a new Linux Mint version and before the final release, translations for all Linux Mint projects are pulled from Launchpad.

**Comment by cypre** [comment]
@xenopeek 

Thank you for your help. And thank you for all the explanations and bits that help me understand it all a bit clearer.

I am glad to have been able to help a little.

Do I close this now? Notice "Close with comment" button beckoning....

**Comment by xenopeek** [comment]
You're welcome and thanks for correcting the translation. Your first GitHub issue solved! We can close this now, I'll do that.
