### ISSUE TITLE
LMDE 5 and Update Manager

### ISSUE THREAD

**Issue by redeemedyo** [linuxmint/mintupdate#732]
Update Manager v. 5.8.2 has "lost" from the View tab, the kernel info mouse click.  This vacated the PC after possibly an upgrade. :<(.  Attempted printscreen/screenshot while tab menu was visable.  Mouse and "magic" key  are not on friendly terms :>).  Did get a screen but not of much importance IMO.  Keep up the good effort!  TTYL  Matin in USA
![LMDE 5 Update Manager View Kernel Issue](https://user-images.githubusercontent.com/57479192/165129352-f9bc31f9-f821-46e9-9433-301b63be668d.png)

**Comment by xenopeek** [comment]
Update Manager on LMDE 5 does not support installing other kernels because the Debian stable package base it uses only supports one kernel release for the duration of its lifetime. The Ubuntu LTS package base used by Linux Mint supports multiple kernel releases (the HWE kernels) during its lifetime, which Update Manager lets you manage.

If you want a different kernel on LMDE 5 you will have to install it manually. There is the option of using Debian backports or Debian unstable. See for example https://forums.linuxmint.com/viewtopic.php?f=250&t=371253. These come with caveats and don't have the same support that HWE kernels on the Ubuntu LTS package base have.

**Comment by clefebvre** [comment]
Kernel management is mint-specific, it's not available in LMDE.
