### ISSUE TITLE
LMDE 5 mintupdate is missing the Kernel Management entry

### ISSUE THREAD

**Issue by Schlumpel** [linuxmint/mintupdate#735]
**Describe the bug**
LMDE 5 mintupdate is missing the Kernel Management entry

**Screenshots**
If applicable, add screenshots to help explain your problem, you can just drag & drop them here.

**To Reproduce**
1. look for a "Kernel Management" entry in the menu, you won't find it

**Expected behavior**
I need the kernel management

**Distribution:**
- [ ] Linux Mint
- [X] LMDE 5
- [ ] Other (please specify)

**Software version:**
5.8.2

**Comment by ImCannibal** [comment]
Verified Still Present in LMDE 6 as of 02jul2024
mintUpdate version 6.0.9

Observe: Kernel Management missing from Update Manager.

Expected Behavior: Kernel Management being present in the Update Manager, identically to the main branch of Mint.

![image](https://github.com/linuxmint/mintupdate/assets/85347373/d4af132f-bbe6-44d6-b5c8-8ce4121f4968)
![image](https://github.com/linuxmint/mintupdate/assets/85347373/37675867-1424-4ea4-a9ff-06449d33b317)

**Comment by ImCannibal** [comment]
Verified Open / Still Present as of 27JUL2024

mintUpdate Version 6.1.5

as per documentation present in mintUpdate "Update Manager"

**Installing and removing kernels
You can install and remove kernels from the Update Manager.
Select "View" -> "Linux Kernels" in the menu.
You cannot remove the kernel you are currently using. To remove it, you need to reboot and select a different kernel to boot with.**

**Observe: Kernel Management missing from Update Manager.

Expected Behavior: Kernel Management being present in the Update Manager of LMDE fork, as in main work of Mint, and Edge, and AS STATED IN THE CONTENTS documentation under Help tab.**

![image](https://github.com/user-attachments/assets/3c53e0de-14cc-4348-a640-c108f6c33df9)

**Comment by mtwebster** [comment]
At the moment neither the Kernel manager or driver managers are available in LMDE editions - this is not a bug.

LMDE is not our primary edition, and Debian is also currently less robust in providing/managing multiple kernels and hardware drivers.
